# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Opérateur défaut: `x %||% y`
#' 
#' @keywords internal
#' @noRd
#' @export
`%||%` <- function(a, b) if (is.null(a)) b else a
