# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Connexion PostgreSQL depuis un fichier YAML
#'
#' Le YAML peut contenir les clés en racine (host, port, dbname/database,
#' user/username, password/pwd, sslmode) ou sous un nœud parmi
#' `postgres`, `default`, `db`, `database`.
#'
#' @param yaml_path Chemin vers le fichier YAML
#'
#' @return Un objet `DBIConnection`
#'
#' @examples
#' \dontrun{
#' con <- connect_pg("path/to/config.yml")
#' DBI::dbDisconnect(con)
#' }
#' @keywords internal
#' @noRd
#' @export
connect_pg <- function(yaml_path) {
  cfg <- yaml::read_yaml(yaml_path)
  src <- cfg
  for (node in c("postgres", "default", "db", "database")) {
    if (is.list(cfg[[node]])) { src <- cfg[[node]]; break }
  }
  host     <- src$host
  port     <- src$port     %||% 5432
  dbname   <- src$dbname   %||% src$database
  user     <- src$user     %||% src$username
  password <- src$password %||% src$pwd
  sslmode  <- src$sslmode  %||% "prefer"

  if (any(vapply(list(host, dbname, user, password), is.null, logical(1)))) {
    stop("YAML incomplet : host, dbname, user, password sont requis.", call. = FALSE)
  }

  DBI::dbConnect(
    RPostgres::Postgres(),
    host = host, port = port, dbname = dbname,
    user = user, password = password, sslmode = sslmode
  )
}
