# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Affiche les guildes écologiques des taxons contributeurs de l’IPR
#'
#' Cette fonction génère un graphique présentant, pour les espèces contributives
#' de l’Indice Poissons Rivière (IPR), les cinq grandes guildes écologiques :
#' \itemize{
#'   \item \strong{réophile} — espèces recherchant les eaux courantes,
#'   \item \strong{lithophile} — espèces pondant sur substrat minéral,
#'   \item \strong{invertivore} — espèces s’alimentant principalement
#'   d’invertébrés,
#'   \item \strong{omnivore} — espèces consommant un régime alimentaire
#'   diversifié,
#'   \item \strong{tolérant} — espèces tolérant des perturbations ou des
#'   conditions dégradées.
#' }
#'
#' Les listes d’espèces de chaque guilde sont codées en dur dans la fonction,
#' conformément aux espèces contributives définies dans les documents de
#' paramétrage de l’IPR (adéquation avec les regroupements du script IPR
#' 1.0.5). Les codes taxons ASPE sont automatiquement convertis en noms
#' vernaculaires via la fonction \code{nom_vernaculaire_aspe()}.
#'
#' Le graphique final comporte une ligne par guilde, avec les noms vernaculaires
#' alignés à gauche et la modalité affichée en gras.
#'
#' @param text_size Taille de la police pour les noms vernaculaires et les titres
#' (défaut : \code{4}).
#' @param width Largeur du graphique (en pouces), mémorisée dans l’attribut
#' \code{"width"} de l’objet ggplot (défaut : \code{10}).
#' @param height Hauteur du graphique (en pouces), mémorisée dans l’attribut
#' \code{"height"} de l’objet ggplot (défaut : \code{6}).
#'
#' @return Un objet \code{ggplot} représentant les guildes écologiques et la
#' liste des espèces associées.  
#' L’objet ggplot possède en attributs \code{"width"} et \code{"height"} les
#' valeurs transmises, pour faciliter l’export (via \code{ggsave}).
#'
#' @details
#' Les cinq vecteurs de taxons codés en dur correspondent strictement aux
#' espèces contributives de l’IPR.  
#' Ils constituent les groupes : réophiles, lithophiles, invertivores,
#' omnivores et tolérants. Les codes taxons sont ensuite convertis en noms
#' vernaculaires dans le graphique final.
#'
#' Le graphique est construit en texte libre (sans axes ni grille), pour
#' produire une représentation claire, lisible et adaptée aux rapports
#' techniques ou aux présentations.  
#' L’alignement à gauche assure une lecture ordonnée des listes d’espèces,
#' triées alphabétiquement au sein de chaque modalité.
#'
#' @examples
#' p <- graph_modalites_ipr(text_size = 4)
#' print(p)
#'
#' # Export recommandé :
#' # ggsave("guildes_ecologiques_IPR.png", p,
#' #        width = attr(p, "width"), height = attr(p, "height"), dpi = 300)
#'
#' @export
graph_modalites_ipr <- function(text_size = 4,
                                width = 10,
                                height = 6) {

  library(dplyr)
  library(ggplot2)
  library(stringr)
  library(ggtext)   # <- nécessaire pour le gras

 
  # 5 VECTEURS CODÉS EN DUR — taxons contributeurs IPR

  vec_reophile    <- c("BLN","LOT","VAX","BAF","BAM","HOT","TOX","CHX","OBX","SAT","SPI","TRF")
  vec_lithophile  <- c("LPX","PHX","BAF","BAM","HOT","TOX","PCH","CHX","OBX","SAT","SPI","TRF")
  vec_invertivore <- c("ANG","GOX","GRE","PES","PCH","CHX","OBX","SAT","SPI","TRF")
  vec_omnivore    <- c("ABL","BRX","CAX","CCO","EPI","GAR","PUX","ROT","SQX","TAN","VAX","TOX")
  vec_tolerant    <- c("ABL","BRX","EPI","GAR","LOX","SQX")

  # Tableau modalité -> codes
  df <- tibble::tibble(
    modalite = c("réophile","lithophile","invertivore","omnivore","tolérant"),
    codes = list(
      vec_reophile,
      vec_lithophile,
      vec_invertivore,
      vec_omnivore,
      vec_tolerant
    )
  ) %>%
    rowwise() %>%
    mutate(
      noms = list(nom_vernaculaire_aspe(codes)),
      ligne = paste0(
        "**", str_to_title(modalite), " :** ",
        paste(sort(unlist(noms)), collapse = ", ")
      )
    ) %>%
    ungroup()


  # Graphique avec RICH TEXT

  p <- ggplot(df, aes(y = rev(modalite), x = 1)) +
    ggtext::geom_richtext(
      aes(label = ligne),
      hjust = 0,
      size = text_size,
      fill = NA,
      label.color = NA
    ) +
    scale_x_continuous(limits = c(1, 2)) +
    theme_minimal() +
    theme(
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank(),
      plot.margin = margin(20, 20, 20, 20)
    )

  attr(p, "width")  <- width
  attr(p, "height") <- height

  return(p)
}
