# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.


#' Commanditaires & Opérateurs ASPE par date
#' Descriptif opération
#'
#' Interroge la base ASPE via un fichier YAML de connexion et extrait,
#' pour une station ou un point ASPE :
#' - Acteurs (panneaux du haut) :
#'   * `commanditaire_libelle_aspe` (panneau "Commanditaire"),
#'   * `operateur_libelle_aspe`     (panneau "Opérateur").
#' - Modes de pêche (panneaux suivants) :
#'   * `protocole_peche`   (panneau "Protocole"),
#'   * `moyen_prospection` (panneau "Prospection").
#' - Comptages (panneau regroupé en bas) :
#'   * `nombre_anodes` + `nombre_epuisettes` (panneau "Matériel").
#'
#' L'axe des x représente les dates (facteur ordonné, dernières dates).
#' Pour Commanditaire/Opérateur/Protocole/Prospection : l'axe y liste les valeurs (un point par présence).
#' Pour Matériel : deux niveaux en y ("Anodes", "Epuisettes"), la valeur (agrégée par date) est inscrite dans le point.
#'
#' @param yaml_path Chemin du YAML de connexion.
#' @param code_station Code station ASPE (prioritaire si fourni avec code_point_prelevement_aspe).
#' @param code_point_prelevement_aspe Code point ASPE.
#' @param annee_debut Année de début de sélection (défaut 1950).
#' @param annee_fin Année de fin de sélection (défaut année courante).
#' @param n_last Nombre de dernières dates distinctes à afficher (défaut 10).
#' @param titre Titre du graphique (défaut : "Descriptif opération").
#' @param normalize_accents Si TRUE, déaccentue les textes (fusionne "À pied"/"A pied").
#'
#' @return Un objet ggplot2 facetté (5 panneaux : Commanditaire, Opérateur,
#'         Protocole, Prospection, Matériel).
#'
#' @export
graph_descriptif_operation <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin = as.integer(format(Sys.Date(), "%Y")),
  n_last = 10,
  titre = "Descriptif opération",
  normalize_accents = TRUE
){
  library(DBI)
  library(dplyr)
  library(ggplot2)
  library(lubridate)
  library(stringr)

  if (!is.null(code_station) & !is.null(code_point_prelevement_aspe)) {
    warning("Les deux paramètres sont fournis : code_station prioritaire.")
  }
  use_station <- !is.null(code_station)

  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con))

  # --- Requête SQL ---
  if (use_station) {
    sql <- glue::glue("
      SELECT
        s.code_station,
        o.date_operation::date AS date_op,
        o.commanditaire_libelle_aspe,
        o.operateur_libelle_aspe,
        o.protocole_peche,
        o.moyen_prospection,
        o.nombre_anodes,
        o.nombre_epuisettes
      FROM qe.aspe_operations o
      LEFT JOIN qe.aspe_stations s
        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe
      WHERE s.code_station = '{code_station}'
        AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN {annee_debut} AND {annee_fin}
      ORDER BY date_op DESC
    ")
  } else {
    sql <- glue::glue("
      SELECT
        s.code_station,
        o.date_operation::date AS date_op,
        o.commanditaire_libelle_aspe,
        o.operateur_libelle_aspe,
        o.protocole_peche,
        o.moyen_prospection,
        o.nombre_anodes,
        o.nombre_epuisettes
      FROM qe.aspe_operations o
      LEFT JOIN qe.aspe_stations s
        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe
      WHERE o.code_point_prelevement_aspe = '{code_point_prelevement_aspe}'
        AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN {annee_debut} AND {annee_fin}
      ORDER BY date_op DESC
    ")
  }

  df <- DBI::dbGetQuery(con, sql)
  if (nrow(df) == 0) return(NULL)

  # --- Nettoyage des libellés ---
  df <- df %>%
    mutate(
      commanditaire_libelle_aspe = na_if(str_squish(trimws(commanditaire_libelle_aspe)), ""),
      operateur_libelle_aspe     = na_if(str_squish(trimws(operateur_libelle_aspe)), ""),
      protocole_peche            = na_if(str_squish(trimws(protocole_peche)), ""),
      moyen_prospection          = na_if(str_squish(trimws(moyen_prospection)), "")
    )

  if (isTRUE(normalize_accents)) {
    if (requireNamespace("stringi", quietly = TRUE)) {
      df <- df %>%
        mutate(
          protocole_peche   = stringi::stri_trans_general(protocole_peche, "Latin-ASCII"),
          moyen_prospection = stringi::stri_trans_general(moyen_prospection, "Latin-ASCII")
        )
    }
  }

  # --- n dernières dates ---
  last_dates <- df %>%
    distinct(date_op) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  # --- Qualitatifs dans facettes dédiées ---
  cmd <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Commanditaire",
              acteur=commanditaire_libelle_aspe, valeur=NA_real_) %>%
    filter(!is.na(acteur)) %>% distinct()

  oper <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Opérateur",
              acteur=operateur_libelle_aspe, valeur=NA_real_) %>%
    filter(!is.na(acteur)) %>% distinct()

  # --- Qualitatifs dans la facette Protocole ---
  protocole <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Protocole",
              acteur=protocole_peche, valeur=NA_real_) %>%
    filter(!is.na(acteur)) %>% distinct()

  prospection <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Prospection",
              acteur=moyen_prospection, valeur=NA_real_) %>%
    filter(!is.na(acteur)) %>% distinct()

  # --- Quantitatifs dans Protocole (agrégation = moyenne) ---
  anodes <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Anodes", acteur="Anodes",
              valeur=as.numeric(nombre_anodes)) %>%
    group_by(date_op, type, acteur) %>%
    summarise(valeur=if(all(is.na(valeur))) NA_real_ else mean(valeur, na.rm=TRUE),
              .groups="drop") %>%
    filter(!is.na(valeur))

  epuisettes <- df %>% semi_join(last_dates, by="date_op") %>%
    transmute(date_op, type="Epuisettes", acteur="Epuisettes",
              valeur=as.numeric(nombre_epuisettes)) %>%
    group_by(date_op, type, acteur) %>%
    summarise(valeur=if(all(is.na(valeur))) NA_real_ else mean(valeur, na.rm=TRUE),
              .groups="drop") %>%
    filter(!is.na(valeur))

  # --- Fusion ---
  df_long <- bind_rows(cmd, oper, protocole, prospection, anodes, epuisettes)

  if (nrow(df_long) == 0) return(NULL)

  # --- Nouveau regroupement en facette Protocole ---
  df_long <- df_long %>%
    mutate(
      facet_type = dplyr::recode(
        type,
        "Anodes"      = "Protocole",
        "Epuisettes"  = "Protocole",
        "Protocole"   = "Protocole",
        "Prospection" = "Protocole",
        .default      = type
      ),
      color_group = type
    )

  df_long$facet_type <- factor(
    df_long$facet_type,
    levels=c("Commanditaire", "Opérateur", "Protocole")
  )

  df_long$date_label <- format(df_long$date_op, "%d/%m/%y")
  df_long$date_label <- factor(df_long$date_label, levels = rev(unique(df_long$date_label)))

  # --- Couleurs ---
  cols <- c(
    "Commanditaire"="#1f78b4",
    "Opérateur"    ="#e31a1c",
    "Protocole"    ="grey40",
    "Prospection"  ="orange",
    "Anodes"       ="#6a3d9a",
    "Epuisettes"   ="#33a02c"
  )

  # --- Graphique ---
  p <- ggplot() +
    # Facettes Commanditaire / Opérateur
    geom_point(
      data = df_long %>% filter(facet_type %in% c("Commanditaire","Opérateur")),
      aes(x=date_label, y=acteur, color=color_group),
      size=3
    ) +
    # Qualitatifs du panneau Protocole
    geom_point(
      data = df_long %>% filter(facet_type=="Protocole" &
                                type %in% c("Protocole","Prospection")),
      aes(x=date_label, y=acteur, color=color_group),
      size=3
    ) +
    # Quantitatifs du panneau Protocole
    geom_point(
      data = df_long %>% filter(facet_type=="Protocole" &
                                type %in% c("Anodes","Epuisettes")),
      aes(x=date_label, y=acteur, color=color_group),
      shape=21, fill="white", size=6, stroke=1.1
    ) +
    geom_text(
      data = df_long %>% filter(facet_type=="Protocole" &
                                type %in% c("Anodes","Epuisettes")),
      aes(x=date_label, y=acteur, label=valeur, color=color_group),
      fontface="bold", size=3
    ) +
    facet_grid(
      rows=vars(facet_type),
      scales="free_y",
      space="free_y",
      switch="y"
    ) +
    scale_color_manual(values=cols) +
    labs(title=titre, x="", y="") +
    theme_bw(base_size=12) +
    theme(
      legend.position="none",
      strip.placement="outside",
      strip.text.y.left=element_text(face="bold"),
      axis.text.x=element_text(angle=90, vjust=0.5, hjust=1),
      plot.title=element_text(face="bold"),
      panel.grid.major.y=element_line(color="#dddddd"),
      panel.spacing.y=unit(10,"pt")
    )

  return(p)
}
