# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Heatmap 3×3 IPR (Attendu × Présent) — entièrement paramétrable
#'
#' Génère la matrice 3×3 croisant :
#' - la probabilité d’occurrence attendue (L1–L2–L3),
#' - l’effectif réellement observé (C1–C2–C3),
#' uniquement sur les taxons contributifs de l’IPR.
#'
#' Permet :
#' - d'afficher ou masquer les titres et valeurs d'axes,
#' - personnaliser les tailles de textes,
#' - personnaliser l'épaisseur des bordures,
#' - fournir un titre ou non,
#' - **exclure des typologies d'opérations** via `libelle_qualification_operation`.
#'
#' @param yaml_path Chemin YAML de connexion PG
#' @param code_operation Code d'opération ASPE (prioritaire si fourni)
#' @param code_station Code Sandre (si code_operation NULL)
#' @param code_point_prelevement_aspe CPP (si station NULL)
#' @param seuil_attendu Seuils L1/L2/L3 (par défaut c(0.6,0.2))
#' @param seuil_abondant Seuil C1 (par défaut 20)
#' @param titre Titre optionnel
#' @param size_labels Taille labels internes
#' @param lineheight_labels Interligne labels internes
#' @param size_axis_text Taille tick labels
#' @param size_axis_title Taille titres axes
#' @param size_title Taille du titre principal
#' @param tile_border_size Épaisseur bordures
#' @param show_axis_text Afficher valeurs axes ?
#' @param show_axis_titles Afficher titres axes ?
#' @param exclure_typologies Typologies ASPE à exclure (défaut "Incorrecte")
#'
#' @return Un ggplot2 3×3
#' @export
ipr_heatmap_3x3 <- function(
  yaml_path,
  code_operation = NULL,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  seuil_attendu   = c(0.6, 0.2),
  seuil_abondant  = 20,
  titre           = NULL,
  size_labels     = 3.8,
  lineheight_labels = 0.9,
  size_axis_text  = 11,
  size_axis_title = 12,
  size_title      = 14,
  tile_border_size = 1.1,
  show_axis_text   = TRUE,
  show_axis_titles = TRUE,
  exclure_typologies = c("Incorrecte")
){
  `%||%` <- function(x, y) if (!is.null(x)) x else y

  
  # Connexion
  
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent=TRUE), add=TRUE)

  
  # 1) Détermination du code opération
  
  if (!is.null(code_operation)) {

    code_op <- code_operation

  } else {

    # Station → prioritaire sur CPP
    if (!is.null(code_station)) {
      filtre_sql <- "s.code_station = $1"
      param1     <- code_station
    } else if (!is.null(code_point_prelevement_aspe)) {
      filtre_sql <- "s.code_point_prelevement_aspe = $1"
      param1     <- code_point_prelevement_aspe
    } else {
      stop("Veuillez fournir code_operation OU code_station OU code_point_prelevement_aspe.")
    }

    
    excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
    
    sql_ops <- glue::glue("
      SELECT o.code_operation
      FROM qe.aspe_operations o
      JOIN qe.aspe_stations s
        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe
      WHERE {filtre_sql}
      {excl_clause}
        AND o.date_operation IS NOT NULL
      ORDER BY o.date_operation::date DESC;
    ")

    ops <- DBI::dbGetQuery(con, sql_ops, params=list(param1))
    if (!nrow(ops)) return(NULL)

    # Toujours la dernière opération chronologiquement
    code_op <- ops$code_operation[1]
  }

  
  # 2) Lecture ipr_compl pour CETTE opération
  
  compl <- DBI::dbGetQuery(
    con,
    "SELECT * FROM qe.aspe_ipr_compl WHERE code_operation=$1;",
    params=list(code_op)
  )
  if (!nrow(compl)) return(NULL)

  
  # 3) Logique IPR — inchangée (ton algorithme exact)
  
  IPR_GROUPS <- c(
    "ABL","ANG","BAF","BAM","BLN","BOU","BRX","CAX","CCO","CHX",
    "EPI","ESX","GAR","GOX","GRE","HOT","LOX","LOT","LPX","OBX",
    "PCH","PER","PES","PHX","PUX","ROT","SAN","SAT","SPI","SQX",
    "TAN","TOX","TRF","VAX"
  )

  NOMS <- c(
    "ABL"="Ablette","ANG"="Anguille","BAF"="Barbeau","BAM"="Barbeau mér.",
    "BLN"="Blageon","BOU"="Bouvière","BRX"="Brème sp.","CAX"="Carassin",
    "CCO"="Carpe","CHX"="Chabot","EPI"="Epinoche","ESX"="Brochet",
    "GAR"="Gardon","GOX"="Goujon","GRE"="Grémille","HOT"="Hotu",
    "LOX"="Loche sp.","LOT"="Lote","LPX"="Lamproie sp.","OBX"="Ombre",
    "PCH"="Poisson chat","PER"="Perche","PES"="Perche soleil",
    "PHX"="Vairon","PUX"="Epinochette","ROT"="Rotengle","SAN"="Sandre",
    "SAT"="Saumon","SPI"="Spirlin","SQX"="Chevesne","TAN"="Tanche",
    "TOX"="Toxostome","TRF"="Truite fario","VAX"="Vandoise"
  )

  df <- data.frame(
    taxon = IPR_GROUPS,
    prob = sapply(IPR_GROUPS, \(g){
      col <- tolower(g)
      if (col %in% names(compl)) compl[[col]][1] else NA_real_
    }),
    eff = sapply(IPR_GROUPS, \(g){
      col <- paste0(tolower(g), "_eff")
      if (col %in% names(compl)) compl[[col]][1] else 0
    })
  )

  df <- df[!(df$eff == 0 & df$prob < 0.05), ]

  df$ligne <- cut(
    df$prob,
    breaks=c(-Inf, seuil_attendu[2], seuil_attendu[1], Inf),
    labels=c("L3","L2","L1"), right=TRUE
  )

  df$colonne <- dplyr::case_when(
    df$eff >= seuil_abondant             ~ "C1",
    df$eff > 0 & df$eff < seuil_abondant ~ "C2",
    df$eff == 0                          ~ "C3"
  )

  df$label <- paste0(
    dplyr::recode(df$taxon, !!!NOMS),
    " (", df$eff, ")"
  )

  grid <- expand.grid(
    ligne   = c("L3","L2","L1"),
    colonne = c("C1","C2","C3")
  )

  grid <- dplyr::left_join(
    grid,
    df |> dplyr::group_by(ligne, colonne) |>
      dplyr::summarise(label = paste(label, collapse="\n"), .groups="drop"),
    by=c("ligne","colonne")
  )

  grid$fill_color <- dplyr::case_when(
    (grid$ligne=="L1" & grid$colonne=="C1") |
      (grid$ligne=="L2" & grid$colonne=="C2") |
      (grid$ligne=="L3" & grid$colonne=="C3") ~ "#4682B4",
    (grid$ligne=="L1" & grid$colonne=="C3") |
      (grid$ligne=="L3" & grid$colonne=="C1") ~ "#B4464B",
    TRUE ~ "#ffec8b"
  )

  p <- ggplot2::ggplot(grid, aes(x = colonne, y = ligne)) +
    ggplot2::geom_tile(
      aes(fill = fill_color),
      color = "black", linewidth = tile_border_size
    ) +
    ggplot2::geom_text(
      aes(label = label),
      size       = size_labels,
      lineheight = lineheight_labels,
      fontface   = "bold"
    ) +
    ggplot2::scale_fill_identity() +
    ggplot2::scale_x_discrete(
      labels=c(
        "C1"=paste0("Eff≥", seuil_abondant),
        "C2"=paste0("0<Eff<", seuil_abondant),
        "C3"="Eff = 0"
      )
    ) +
    ggplot2::scale_y_discrete(
      labels=c(
        "L1"=sprintf("Prob > %.2f", seuil_attendu[1]),
        "L2"=sprintf("%.2f ≥ Prob > %.2f", seuil_attendu[1], seuil_attendu[2]),
        "L3"=sprintf("0 < Prob ≤ %.2f",  seuil_attendu[2])
      )
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.x = if (show_axis_text) ggplot2::element_text(size=size_axis_text)
                    else ggplot2::element_blank(),
      axis.text.y = if (show_axis_text) ggplot2::element_text(size=size_axis_text)
                    else ggplot2::element_blank(),
      axis.title.x = if (show_axis_titles) ggplot2::element_text(size=size_axis_title, face="bold")
                     else ggplot2::element_blank(),
      axis.title.y = if (show_axis_titles) ggplot2::element_text(size=size_axis_title, face="bold")
                     else ggplot2::element_blank()
    ) +
    ggplot2::labs(
      x = "Effectif observé",
      y = "Probabilité selon IPR"
    )

  if (!is.null(titre)) {
    p <- p +
      ggplot2::ggtitle(titre) +
      ggplot2::theme(plot.title = ggplot2::element_text(
        size = size_title, face="bold"
      ))
  }

  return(p)
}
