# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse opération pêches électriques (protocole, puissance, ...)
#'
#' @param yaml_path Chemin du YAML de connexion
#' @param station Code Sandre
#' @param annee_debut Année de début (défaut 1950)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param schema Schéma SQL (défaut "qe")
#' @param titre Titre principal (défaut: "<station> — Synthèse opérations")
#' @param sous_titre Sous-titre (défaut: "synthèse générée le <date> par Eaux & Vilaine")
#' @param file_out Chemin de sauvegarde (PNG) si non NULL
#' @param width Largeur (pouces), défaut A4 paysage
#' @param height Hauteur (pouces), défaut A4 paysage
#' @param dpi DPI pour l'export
#' @param n_last Nombre maximum de campagnes affichées
#'
#' @return Un objet `ggplot` (composé avec `cowplot`)
#'
#' @examples
#' \dontrun{
#' make_operations_peche_planche(".../config.yml", "04216050", annee_debut = 2000, n_last = 12)
#' }
#' @export
make_operations_peche_planche <- function(
  yaml_path,
  station,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema     = "qe",
  titre      = NULL,
  sous_titre = NULL,
  file_out   = NULL,
  width      = 29.7 / 2.54,
  height     = 21 / 2.54,
  dpi        = 300,
  n_last     = 12
){
  if (is.null(titre))      titre      <- glue::glue("{station} — Synthèse opérations de pêche")
  if (is.null(sous_titre)) sous_titre <- glue::glue("Synthèse réalisée le {format(Sys.Date(), '%d/%m/%Y')} par Eaux & Vilaine")
  
  graph_operations <- graph_descriptif_operation(
  yaml_path    = yaml_path,
  code_station = station,
  annee_debut  = annee_debut,
  annee_fin    = annee_fin,
  n_last = n_last
  )
  
  graph_long_station <- plot_longueur_pechee_histogram(yaml_path, 
                                         code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
  
    graph_largeur_station <- plot_largeur_lame_eau_pechee_histogram(yaml_path, 
                                         code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
  
  graph_profond <- plot_profondeur_histogram(yaml_path, 
                                             code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
  
    graph_conductivite <- plot_conductivite_pechee_histogram(yaml_path, 
                                             code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
    
    graph_temperature <- plot_temperature_instantanee_pechee_histogram(yaml_path, 
                                             code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
    

    graph_puissance<-plot_puissance_pechee_histogram(yaml_path, 
                                             code_station=station, 
                                         annee_debut=annee_debut, 
                                         annee_fin=annee_fin, 
                                         n_last = n_last)
    
    
  if (is.null(graph_puissance) && is.null(graph_temperature) && 
      is.null(graph_conductivite) && is.null(graph_profond) &&
      is.null(graph_largeur_station) && is.null(graph_long_station) &&
      is.null(graph_operations)) return(NULL)

  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(plot.title = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
                   plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5))
  block_droit <- cowplot::plot_grid(graph_long_station, 
                                    graph_largeur_station,
                                    graph_profond, 
                                    graph_conductivite,
                                    graph_temperature,
                                    graph_puissance, 
                                    nrow = 3)
  block_graphs <- cowplot::plot_grid(graph_operations, block_droit, nrow = 1, rel_widths = c(2.5, 1))
  planche      <- cowplot::plot_grid(title_gg, block_graphs, nrow = 2, rel_heights = c(0.4, 3))

  if (!is.null(file_out)) {
    cowplot::save_plot(filename = file_out, plot = planche, base_width = width, base_height = height, dpi = dpi, bg = "white")
  }
  planche
}


