# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse habitats pêches électriques (faciès, profondeur, ...)
#'
#' @param yaml_config Chemin du YAML de connexion
#' @param station Code Sandre
#' @param annee_debut Année de début (défaut 1950)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param indicateurs Vecteur d'indicateurs pour les métriques
#' @param schema Schéma SQL (défaut "qe")
#' @param titre Titre principal (défaut: "<station> — Synthèse habitats")
#' @param sous_titre Sous-titre (défaut: "synthèse générée le <date> par Eaux & Vilaine")
#' @param file_out Chemin de sauvegarde (PNG) si non NULL
#' @param width Largeur (pouces), défaut A4 paysage
#' @param height Hauteur (pouces), défaut A4 paysage
#' @param dpi DPI pour l'export
#' @param n_last Nombre maximum de campagnes affichées
#'
#' @return Un objet `ggplot` (composé avec `cowplot`)
#'
#' @examples
#' \dontrun{
#' make_ipr_planche(".../config.yml", "04216050", annee_debut = 2000, n_last = 12)
#' }
#' @export
#' @noRd  
make_habitats_peche_planche <- function(
  yaml_config,
  station,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  indicateurs = c("DII","DIO","DIT","DTI","NEL","NER","NTE"),
  schema     = "qe",
  titre      = NULL,
  sous_titre = NULL,
  file_out   = NULL,
  width      = 29.7 / 2.54,
  height     = 21 / 2.54,
  dpi        = 300,
  n_last     = 12
){
  if (is.null(titre))      titre      <- glue::glue("{station} — Synthèse IPR")
  if (is.null(sous_titre)) sous_titre <- glue::glue("synthèse générée le {format(Sys.Date(), '%d/%m/%Y') par Eaux & Vilaine}")

  graph_ipr <- plot_ipr_histogram(yaml_config, station, annee_debut, annee_fin, schema, n_last = n_last)
  graph_eff <- plot_effectifs_histogram(yaml_config, station, annee_debut, annee_fin, schema, only_with_ipr = TRUE, n_last = n_last)
  graph_met <- plot_ipr_metrics(yaml_config, station, indicateurs, annee_debut, annee_fin, schema, table = "aspe_ipr",
                                n_lignes_facets = 2, n_last = n_last)

  if (is.null(graph_ipr) && is.null(graph_eff) && is.null(graph_met)) return(NULL)

  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(plot.title = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
                   plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5))
  block_top    <- cowplot::get_title(title_gg)
  block_middle <- cowplot::plot_grid(graph_ipr, graph_eff, nrow = 1, rel_widths = c(3, 2))
  planche      <- cowplot::plot_grid(block_top, block_middle, graph_met, nrow = 3, rel_heights = c(0.20, 1, 2))

  if (!is.null(file_out)) {
    cowplot::save_plot(filename = file_out, plot = planche, base_width = width, base_height = height, dpi = dpi, bg = "white")
  }
  planche
}


