# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse IPR (notes, effectifs, métriques)
#'
#' Crée une planche complète combinant :
#' - histogramme des notes IPR,
#' - histogramme des effectifs,
#' - histogramme des métriques IPR (observé vs modélisé).
#'
#' Toutes les opérations dont la qualification (`libelle_qualification_operation`
#' dans la table `aspe_operations`) appartient au vecteur
#' `exclure_typologies` sont exclues.
#'
#' @param yaml_path Chemin du fichier YAML de connexion PostgreSQL.
#' @param station Code Sandre de la station.
#' @param annee_debut Année de début (défaut `1950`).
#' @param annee_fin Année de fin (défaut = année courante).
#' @param indicateurs Vecteur d'indicateurs IPR (défaut :
#'   `c("DII","DIO","DIT","DTI","NEL","NER","NTE")`).
#' @param schema Schéma SQL contenant les tables IPR (défaut `"qe"`).
#' @param titre Titre principal (généré automatiquement si `NULL`).
#' @param sous_titre Sous-titre (généré automatiquement si `NULL`).
#' @param file_out Fichier PNG de sortie. Si `NULL`, aucun export.
#' @param width Largeur du PNG (en pouces).
#' @param height Hauteur du PNG (en pouces).
#' @param dpi Résolution du PNG.
#' @param n_last Nombre maximum de dates de campagnes à afficher (défaut : 12).
#' @param exclure_typologies Vecteur des typologies d'opération à exclure
#'   (défaut : `"Incorrecte"`).
#'
#' @return Un objet ggplot/cowplot représentant la planche, ou `NULL` si aucune donnée.
#' @export
make_ipr_planche <- function(
  yaml_path,
  station,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  indicateurs = c("DII","DIO","DIT","DTI","NEL","NER","NTE"),
  schema = "qe",
  titre = NULL,
  sous_titre = NULL,
  file_out = NULL,
  width = 29.7 / 2.54,
  height = 21 / 2.54,
  dpi = 300,
  n_last = 12,
  exclure_typologies = c("Incorrecte")   # <-- NOUVEAU
){
  require(DBI); require(glue); require(cowplot)
  `%||%` <- function(x, y) if (!is.null(x)) x else y


  # Connexion

  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)


  # Génération des titres automatiques via meta

  info_titres <- .aspe_fetch_meta_and_titles(
    con = con,
    schema = schema %||% "qe",
    station = station,
    code_point_prelevement_aspe = NULL,
    default_title_suffix = " — Synthèse IPR",
    default_subtitle_prefix = "Synthèse réalisée le "
  )

  if (is.null(titre))      titre      <- info_titres$titre_auto
  if (is.null(sous_titre)) sous_titre <- info_titres$sous_titre_auto

  schema_safe <- sanitize_schema(schema)
  tbl_ipr_compl <- sprintf('"%s".aspe_ipr_compl',  schema_safe)
  tbl_ops       <- sprintf('"%s".aspe_operations', schema_safe)


  # Extraction des opérations IPR pour la station + EXCLUSION TYPOLOGIES

  sql_ops <- glue::glue("
    SELECT c.code_operation, o.date_operation
    FROM {tbl_ipr_compl} c
    JOIN {tbl_ops} o
      ON c.code_operation = o.code_operation
    WHERE c.code_station = $1
      AND NOT (o.libelle_qualification_operation = ANY($2))
  ")

  ops <- DBI::dbGetQuery(
    con,
    sql_ops,
    params = list(station, exclure_typologies)  # <-- NOUVEAU
  )
  if (!nrow(ops)) return(NULL)


  # Parsing dates ISO

  parse_iso <- function(x){
    x2 <- gsub("Z$", "+00:00", x)
    out <- suppressWarnings(as.POSIXct(x2, format="%Y-%m-%dT%H:%M:%OS%z"))
    bad <- is.na(out)
    if (any(bad)) out[bad] <- suppressWarnings(as.POSIXct(x[bad], format="%Y-%m-%d"))
    out
  }

  ops$dt    <- parse_iso(ops$date_operation)
  ops$annee <- as.integer(format(ops$dt,"%Y"))

  # Filtre années
  ops <- ops[ops$annee >= annee_debut & ops$annee <= annee_fin, ]
  if (!nrow(ops)) return(NULL)

  # Garder les n dernières opérations
  ops <- ops[order(ops$dt, decreasing = TRUE), ]
  ops <- ops[seq_len(min(n_last, nrow(ops))), ]
  ops <- ops[order(ops$dt), ]


  # Génération des vignettes (avec exclusion typologies)

  graph_ipr <- plot_ipr_histogram(
    yaml_path = yaml_path,
    station   = station,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    schema      = schema_safe,
    n_last      = n_last,
    exclure_typologies = exclure_typologies   # <-- NOUVEAU
  )

  graph_eff <- plot_effectifs_histogram(
    yaml_path = yaml_path,
    station   = station,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    schema      = schema_safe,
    only_with_ipr = TRUE,
    n_last      = n_last,
    exclure_typologies = exclure_typologies   # <-- NOUVEAU
  )

  graph_met <- plot_ipr_metrics(
    yaml_path = yaml_path,
    station   = station,
    indicateurs = indicateurs,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    schema      = schema_safe,
    n_last      = n_last,
    exclure_typologies = exclure_typologies   # <-- NOUVEAU
  )

  if (is.null(graph_ipr) & is.null(graph_eff) & is.null(graph_met))
    return(NULL)


  # Mise en page

  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title    = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5)
    )

  block_middle <- cowplot::plot_grid(
    graph_ipr, graph_eff,
    nrow = 1, rel_widths = c(3, 2)
  )

  planche <- cowplot::plot_grid(
    title_gg,
    block_middle,
    graph_met,
    nrow = 3,
    rel_heights = c(0.40, 1, 2)
  )


  # Export PNG éventuel

  if (!is.null(file_out)) {
    cowplot::save_plot(
      filename = file_out,
      plot     = planche,
      base_width  = width,
      base_height = height,
      dpi         = dpi,
      bg          = "white"
    )
  }

  return(planche)
}

