# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche IPR — Analyse des n dernières opérations d'une station
#'
#' @description
#' Génère une planche composée des **n dernières vignettes IPR 3×3** réalisées
#' sur une station donnée.  
#'
#' Chaque vignette est produite via `ipr_heatmap_3x3()` avec :
#'
#' - **valeurs d’axes visibles** (`show_axis_text = TRUE`) ;
#' - **titres d’axes masqués** (`show_axis_titles = FALSE`) afin de mutualiser
#'   les titres dans la planche finale ;
#' - un **titre local** correspondant à la date de l’opération (jj/mm/aa).  
#'
#' La planche :
#'
#' - est triée **du plus ancien au plus récent** ;
#' - est affichée en grille (4 colonnes × plusieurs lignes) ;
#' - possède un **titre global**, un **axe X commun**, un **axe Y commun** ;
#' - peut afficher un panneau final `graph_modalites_ipr()` listant les guildes
#'   écologiques (option `affiche_guildes_eco`).
#'
#' @details
#' Étapes exécutées :
#'
#' 1. Connexion PostgreSQL via YAML.
#' 2. Extraction des opérations IPR de `schema.aspe_ipr_compl`
#'    rejointes à `schema.aspe_operations`.
#' 3. Filtrage années.
#' 4. Sélection des `n_last` dernières dates.
#' 5. Génération d'une vignette avec `ipr_heatmap_3x3()` par opération.
#' 6. Construction de la grille.
#' 7. Ajout titre général + axes mutualisés.
#' 8. Export PNG optionnel.
#'
#' @param yaml_path Chemin du fichier YAML de connexion.
#' @param station Code Sandre de la station (obligatoire).
#' @param annee_debut Année minimale (défaut 1950).
#' @param annee_fin Année maximale (défaut = année courante).
#' @param schema Schéma SQL (défaut `"qe"`).
#' @param titre Titre global. Généré automatiquement si `NULL`.
#' @param sous_titre Sous‑titre global. Automatique si `NULL`.
#' @param file_out Export PNG (chemin du fichier).  
#'                 Si `NULL`, aucun export n’est réalisé.
#' @param width Largeur en pouces (défaut A4 paysage).
#' @param height Hauteur en pouces (défaut A4 paysage).
#' @param dpi Résolution (défaut 300).
#' @param n_last Nombre maximum d’opérations (défaut 12).
#' @param affiche_guildes_eco Si TRUE, ajoute `graph_modalites_ipr()`.
#' @param exclure_typologies Vecteur des typologies ASPE à exclure  
#'        (défaut `c("Incorrecte")`).
#' @param ... Arguments additionnels transmis à `ipr_heatmap_3x3()`.
#'
#' @return Un objet cowplot (la planche IPR).  
#'         Retourne `NULL` si aucune opération n’est disponible.
#'
#' @export
make_analyse_pop_IPR_planche <- function(
  yaml_path,
  station,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema      = "qe",
  titre       = NULL,
  sous_titre  = NULL,
  file_out    = NULL,
  width       = 29.7/2.54,
  height      = 21/2.54,
  dpi         = 300,
  n_last      = 12,
  affiche_guildes_eco = TRUE,
  exclure_typologies = c("Incorrecte"),   # <-- NOUVEAU PARAMÈTRE
  ...
){
  `%||%` <- function(x,y) if (!is.null(x)) x else y

  
  # Connexion & métadonnées station
  
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con)), add = TRUE)

  info_titres <- .aspe_fetch_meta_and_titles(
    con = con,
    schema = schema,
    station = station,
    code_point_prelevement_aspe = NULL,
    default_title_suffix  = " — Effectifs pêchés vs attendus (IPR)",
    default_subtitle_prefix = "Synthèse réalisée le "
  )

  if (is.null(titre))      titre      <- info_titres$titre_auto
  if (is.null(sous_titre)) sous_titre <- info_titres$sous_titre_auto

  
  # Extraction DES OPERATIONS IPR (AVEC EXCLUSION TYPOLOGIES)
  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue::glue("
    SELECT c.code_operation, o.date_operation
    FROM   \"{schema}\".aspe_ipr_compl c
    JOIN   \"{schema}\".aspe_operations o
           ON c.code_operation = o.code_operation
    WHERE  c.code_station = $1
{excl_clause}
  ")

  ops <- DBI::dbGetQuery(
    con,
    sql,
    params = list(station)   # <-- application du filtre
  )
  if (!nrow(ops)) return(NULL)

  
  # Nettoyage des dates (ISO / format hub'eau)
  
  parse_iso <- function(x){
    x2  <- gsub("Z$","+00:00",x)
    out <- suppressWarnings(as.POSIXct(x2, format="%Y-%m-%dT%H:%M:%OS%z"))
    bad <- is.na(out)
    if (any(bad)) out[bad] <- suppressWarnings(as.POSIXct(x[bad], format="%Y-%m-%d"))
    out
  }

  ops$dt    <- parse_iso(ops$date_operation)
  ops$annee <- as.integer(format(ops$dt,"%Y"))
  ops       <- ops[ops$annee >= annee_debut & ops$annee <= annee_fin, ]
  if (!nrow(ops)) return(NULL)

  
  # Sélection des N dernières opérations, puis tri chronologique
  
  ops <- ops[order(ops$dt, decreasing=TRUE), ]
  ops <- ops[seq_len(min(n_last, nrow(ops))), ]
  ops <- ops[order(ops$dt), ]

  fmt_date <- function(x) format(x,"%d/%m/%y")
  plots    <- vector("list", nrow(ops))

  
  # Génération des vignettes IPR 3×3
  
  for (i in seq_len(nrow(ops))) {

    code_op <- ops$code_operation[i]
    dt_lab  <- fmt_date(ops$dt[i])

    p <- try(
      ipr_heatmap_3x3(
        yaml_path = yaml_path,
        code_operation = code_op,
        titre = NULL,
        show_axis_text   = TRUE,
        show_axis_titles = FALSE,
        size_labels      = 2.8,
        lineheight_labels = 0.85,
        size_axis_text    = 7,
        size_axis_title   = 8,
        tile_border_size  = 0.6,
        exclure_typologies = exclure_typologies,   # <-- transmis !
        ...
      ),
      silent = TRUE
    )

    if (inherits(p, "try-error")) {
      p <- ggplot2::ggplot() +
        ggplot2::geom_text(
          ggplot2::aes(0,0,label=paste0("Erreur ", code_op))
        ) +
        ggplot2::theme_void()
    } else {
      p <- p + ggplot2::ggtitle(dt_lab) +
        ggplot2::theme(plot.title=ggplot2::element_text(size=9, face="bold"))
    }

    plots[[i]] <- p
  }

  
  # Mutualisation des axes
  
  xlab_common <- ggplot2::ggplot() +
    ggplot2::labs(x="Effectif capturé") +
    ggplot2::theme_void() +
    ggplot2::theme(axis.title.x=ggplot2::element_text(size=12, face="bold"))

  ylab_common <- ggplot2::ggplot() +
    ggplot2::labs(y="Probabilité selon IPR") +
    ggplot2::theme_void() +
    ggplot2::theme(axis.title.y=ggplot2::element_text(size=12, face="bold", angle=90))

  
  # Grille principale (4 colonnes)
  
  grid_plots <- cowplot::plot_grid(plotlist=plots, ncol=4)

  grid_with_y <- cowplot::plot_grid(
    ylab_common, grid_plots,
    ncol=2, rel_widths=c(0.04,1)
  )

  grid_with_xy <- cowplot::plot_grid(
    grid_with_y, xlab_common,
    nrow=2, rel_heights=c(1,0.07)
  )

  
  # Titre principal
  
  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title=titre, subtitle=sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title=ggplot2::element_text(size=16, face="bold", hjust=0.5)
    )

  planche <- cowplot::plot_grid(
    title_gg, grid_with_xy,
    nrow=2, rel_heights=c(0.15,1)
  )

  
  # Affichage des guildes écologiques (optionnel)
  
  if (affiche_guildes_eco) {
    planche <- cowplot::plot_grid(
      planche,
      graph_modalites_ipr(text_size = 3),
      nrow = 2,
      rel_heights = c(20, 2.5)
    )
  }

  
  # Export PNG
  
  if (!is.null(file_out)) {
    cowplot::save_plot(
      file_out,
      planche,
      base_width  = width,
      base_height = height,
      dpi         = dpi,
      bg          = "white"
    )
  }

  return(planche)
}
