# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse des opérations de pêche électrique (protocole, longueurs, largeurs, puissance, etc.)
#'
#' Produit une planche complète combinant :
#' - un descriptif des opérations (protocole, durées, volumes, etc.),
#' - un histogramme des longueurs pêchées,
#' - un histogramme des largeurs de lame d'eau,
#' - un histogramme des profondeurs,
#' - un histogramme des conductivités,
#' - un histogramme des températures instantanées,
#' - un histogramme des puissances.
#'
#' Toutes les opérations incluses sont filtrées selon :
#' - station OU CPP,
#' - l’intervalle d’années,
#' - les `n_last` dernières dates distinctes,
#' - la typologie d’opération (`libelle_qualification_operation`) à exclure
#'   via `exclure_typologies`.
#'
#' @param yaml_path Fichier YAML de connexion PostgreSQL
#' @param station Code Sandre de la station (prioritaire si renseigné)
#' @param code_point_prelevement_aspe Code ASPE si station non renseignée
#' @param annee_debut Année minimale (défaut 1950)
#' @param annee_fin Année maximale (défaut année courante)
#' @param schema Schéma SQL (défaut `"qe"`)
#' @param titre Titre principal (auto si NULL)
#' @param sous_titre Sous-titre (auto si NULL)
#' @param file_out Chemin PNG à générer (NULL = pas d’export)
#' @param width Largeur en pouces
#' @param height Hauteur en pouces
#' @param dpi Résolution PNG
#' @param n_last Nombre de dernières dates distinctes à afficher
#' @param exclure_typologies Typologies d’opérations à exclure (défaut `"Incorrecte"`)
#'
#' @return Un objet cowplot ou NULL
#' @export
make_operations_peche_planche <- function(
  yaml_path,
  station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema      = "qe",
  titre       = NULL,
  sous_titre  = NULL,
  file_out    = NULL,
  width       = 29.7 / 2.54,
  height      = 21   / 2.54,
  dpi         = 300,
  n_last      = 12,
  exclure_typologies = c("Incorrecte")   # <-- [NOUVEAU PARAMÈTRE]
){
  require(DBI); require(glue); require(cowplot)

 
  # 1) Validation station / CPP
 
  if (is.null(station) && is.null(code_point_prelevement_aspe)) {
    stop("Veuillez fournir `station` OU `code_point_prelevement_aspe`.", call. = FALSE)
  }

 
  # 2) Connexion & tables
 
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_sta     <- sprintf('"%s".aspe_stations',    schema_safe)

  # Choisir le filtre pour récupérer les métadonnées titres
  if (!is.null(station)) {
    filtre_sql <- "s.code_station = $1"
    param1     <- station
  } else {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

 
  # 3) Métadonnées pour titre automatique
 
  meta_sql <- glue("
    SELECT 
      s.code_station, s.libelle_station,
      s.code_point_prelevement_wama, s.libelle_point_prelevement_wama
    FROM {tbl_sta} s
    WHERE {filtre_sql}
    LIMIT 1;
  ")

  meta <- tryCatch(DBI::dbGetQuery(con, meta_sql, params = list(param1)),
                   error = function(e) NULL)

  if (is.data.frame(meta) && nrow(meta) == 1 &&
      !is.na(meta$code_station[1]) && nzchar(meta$code_station[1]) &&
      !is.na(meta$libelle_station[1]) && nzchar(meta$libelle_station[1])) {

    titre_auto <- paste0(meta$code_station[1], " — ", meta$libelle_station[1])

  } else if (is.data.frame(meta) && nrow(meta) == 1) {

    titre_auto <- paste0(
      ifelse(is.na(meta$code_point_prelevement_wama[1]), "", meta$code_point_prelevement_wama[1]),
      " — ",
      ifelse(is.na(meta$libelle_point_prelevement_wama[1]), "", meta$libelle_point_prelevement_wama[1])
    )

  } else {
    # Pas trouvé dans aspe_stations
    titre_auto <- if (!is.null(station)) station else code_point_prelevement_aspe
  }

  if (is.null(titre)) {
    titre <- glue("{titre_auto} — Synthèse opérations de pêche")
  }
  if (is.null(sous_titre)) {
    sous_titre <- glue("Synthèse réalisée le {format(Sys.Date(), '%d/%m/%Y')} par Eaux & Vilaine")
  }

 
  # 4) Sous‑graphes — tous enrichis avec `exclure_typologies`
 

  graph_operations <- graph_descriptif_operation(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_long_station <- plot_longueur_pechee_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_largeur_station <- plot_largeur_lame_eau_pechee_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_profond <- plot_profondeur_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_conductivite <- plot_conductivite_pechee_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_temperature <- plot_temperature_instantanee_pechee_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_puissance <- plot_puissance_pechee_histogram(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

 
  # 5) Si toutes les sous-figures sont NULL → RETURN(NULL)
 
  if (all(vapply(
    list(
      graph_puissance,
      graph_temperature,
      graph_conductivite,
      graph_profond,
      graph_largeur_station,
      graph_long_station,
      graph_operations
    ),
    is.null, logical(1)
  ))) {
    return(NULL)
  }

 
  # 6) Composition de la planche
 
  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title    = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5)
    )

  block_droit <- cowplot::plot_grid(
    graph_long_station,
    graph_largeur_station,
    graph_profond,
    graph_conductivite,
    graph_temperature,
    graph_puissance,
    nrow = 3
  )

  block_graphs <- cowplot::plot_grid(
    graph_operations,
    block_droit,
    nrow = 1,
    rel_widths = c(2.5, 1)
  )

  planche <- cowplot::plot_grid(
    title_gg,
    block_graphs,
    nrow = 2,
    rel_heights = c(0.4, 3)
  )

 
  # 7) Export PNG optionnel
 
  if (!is.null(file_out)) {
    cowplot::save_plot(
      filename    = file_out,
      plot        = planche,
      base_width  = width,
      base_height = height,
      dpi         = dpi,
      bg          = "white"
    )
  }

  return(planche)
}

