# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse opération pêches électriques (protocole, puissance, ...) — station OU CPP
#'
#' @param yaml_path Chemin du YAML de connexion
#' @param station Code Sandre (ou NULL si CPP fourni)
#' @param code_point_prelevement_aspe Code du point ASPE (ou NULL si station fourni)
#' @param annee_debut Année de début (défaut 1950)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param schema Schéma SQL (défaut "qe")
#' @param titre Titre principal (défaut auto : "CODE — LIBELLÉ — Synthèse opérations de pêche" ou WAMA)
#' @param sous_titre Sous-titre (défaut: "Synthèse réalisée le <date> par Eaux & Vilaine")
#' @param file_out Chemin de sauvegarde (PNG) si non NULL
#' @param width Largeur (pouces), défaut A4 paysage
#' @param height Hauteur (pouces), défaut A4 paysage
#' @param dpi DPI pour l'export
#' @param n_last Nombre maximum de campagnes affichées (par dates distinctes)
#'
#' @return Un objet `ggplot` (composé avec `cowplot`) ou NULL si aucune sous-figure disponible
#' @export
make_operations_peche_planche <- function(
  yaml_path,
  station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema      = "qe",
  titre       = NULL,
  sous_titre  = NULL,
  file_out    = NULL,
  width       = 29.7 / 2.54,
  height      = 21   / 2.54,
  dpi         = 300,
  n_last      = 12
){
  require(DBI); require(glue); require(cowplot)

  # ------------------------------------------------------------
  # 1) Validation : station OU CPP
  # ------------------------------------------------------------
  if (is.null(station) && is.null(code_point_prelevement_aspe)) {
    stop("Veuillez fournir `station` OU `code_point_prelevement_aspe`.", call. = FALSE)
  }

  # ------------------------------------------------------------
  # 2) Connexion + tables sécurisées
  # ------------------------------------------------------------
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_sta     <- sprintf('"%s".aspe_stations', schema_safe)

  # ------------------------------------------------------------
  # 3) Récupération du titre automatique (station/WAMA/CPP)
  #    - station fournie -> filtre station
  #    - CPP -> on tente via aspe_stations ; sinon fallback = code CPP
  # ------------------------------------------------------------
  if (!is.null(station)) {
    filtre_sql <- "s.code_station = $1"
    param1     <- station
  } else {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  meta_sql <- glue::glue("
    SELECT 
      s.code_station, s.libelle_station,
      s.code_point_prelevement_wama, s.libelle_point_prelevement_wama
    FROM {tbl_sta} s
    WHERE {filtre_sql}
    LIMIT 1;
  ")

  meta <- tryCatch(DBI::dbGetQuery(con, meta_sql, params = list(param1)),
                   error = function(e) NULL)

  if (is.data.frame(meta) && nrow(meta) == 1 &&
      !is.na(meta$code_station[1]) && nzchar(meta$code_station[1]) &&
      !is.na(meta$libelle_station[1]) && nzchar(meta$libelle_station[1])) {
    titre_auto <- paste0(meta$code_station[1], " — ", meta$libelle_station[1])
  } else if (is.data.frame(meta) && nrow(meta) == 1) {
    cs <- meta$code_point_prelevement_wama[1]
    ls <- meta$libelle_point_prelevement_wama[1]
    titre_auto <- paste0(ifelse(is.na(cs), "", cs), " — ", ifelse(is.na(ls), "", ls))
  } else {
    # Fallback minimal si aucune ligne en table stations
    titre_auto <- if (!is.null(station)) station else code_point_prelevement_aspe
  }

  if (is.null(titre)) {
    titre <- glue::glue("{titre_auto} — Synthèse opérations de pêche")
  }
  if (is.null(sous_titre)) {
    sous_titre <- glue::glue("Synthèse réalisée le {format(Sys.Date(), '%d/%m/%Y')} par Eaux & Vilaine")
  }

  # ------------------------------------------------------------
  # 4) Sous-graphes (tous station OU CPP) — signatures homogènes
  # ------------------------------------------------------------
  graph_operations <- graph_descriptif_operation(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last
  )

  graph_long_station <- plot_longueur_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  graph_largeur_station <- plot_largeur_lame_eau_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  graph_profond <- plot_profondeur_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  graph_conductivite <- plot_conductivite_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  graph_temperature <- plot_temperature_instantanee_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  graph_puissance <- plot_puissance_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last
  )

  # ------------------------------------------------------------
  # 5) Si aucune sous-figure disponible -> NULL
  # ------------------------------------------------------------
  if (is.null(graph_puissance)       &&
      is.null(graph_temperature)     &&
      is.null(graph_conductivite)    &&
      is.null(graph_profond)         &&
      is.null(graph_largeur_station) &&
      is.null(graph_long_station)    &&
      is.null(graph_operations)) {
    return(NULL)
  }

  # ------------------------------------------------------------
  # 6) Composition de la planche
  # ------------------------------------------------------------
  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title    = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5)
    )+ ggplot2::theme(
    plot.background  = ggplot2::element_rect(fill = "white", colour = NA),
    panel.background = ggplot2::element_rect(fill = "white", colour = NA)
  )

  block_droit <- cowplot::plot_grid(
    graph_long_station,
    graph_largeur_station,
    graph_profond,
    graph_conductivite,
    graph_temperature,
    graph_puissance,
    nrow = 3
  )

  block_graphs <- cowplot::plot_grid(
    graph_operations,
    block_droit,
    nrow = 1, rel_widths = c(2.5, 1)
  )

  planche <- cowplot::plot_grid(
    title_gg,
    block_graphs,
    nrow = 2, rel_heights = c(0.4, 3)
  )
  
planche <- cowplot::ggdraw(planche) +
  ggplot2::theme(
    plot.background = ggplot2::element_rect(fill = "white", colour = NA)
  )


  # ------------------------------------------------------------
  # 7) Export optionnel
  # ------------------------------------------------------------
  if (!is.null(file_out)) {
    cowplot::save_plot(
      filename    = file_out,
      plot        = planche,
      base_width  = width,
      base_height = height,
      dpi         = dpi,
      bg          = "white"
    )
  }

  return(planche)
}


