# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche synthèse habitats pêches électriques (faciès, profondeur, surface, habitats)
#'
#' Produit une planche complète combinant :
#' - un heatmap des habitats (conditions / faciès / hydrologie),
#' - un histogramme des faciès,
#' - un histogramme des profondeurs,
#' - un histogramme des surfaces pêchées.
#'
#' Toutes les fonctions sous‑jacentes appliquent un même filtrage des opérations
#' via `libelle_qualification_operation`, selon l’argument `exclure_typologies`.
#'
#' Fonctionne pour une station `code_station` (via aspe_stations) ou un point
#' ASPE orphelin `code_point_prelevement_aspe` (sans JOIN).
#'
#' @param yaml_path Fichier YAML de connexion PostgreSQL.
#' @param station Code Sandre (prioritaire si fourni).
#' @param code_point_prelevement_aspe Code ASPE si `station` n’est pas fourni.
#' @param annee_debut Année minimale (défaut 1950).
#' @param annee_fin Année maximale (défaut = année courante).
#' @param schema Schéma SQL (défaut `"qe"`).
#' @param titre Titre principal (auto si NULL).
#' @param sous_titre Sous‑titre (auto si NULL).
#' @param file_out Chemin PNG à générer (NULL = pas d’export).
#' @param width Largeur (pouces ; défaut A4 paysage).
#' @param height Hauteur (pouces ; défaut A4 paysage).
#' @param dpi DPI export.
#' @param n_last Nombre maximum de campagnes à afficher.
#' @param exclure_typologies Vecteur des typologies d’opérations à exclure
#'   (défaut `"Incorrecte"`).
#'
#' @return Un objet ggplot/cowplot, ou NULL si aucune donnée.
#' @export
make_habitats_peche_planche <- function(
  yaml_path,
  station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema      = "qe",
  titre       = NULL,
  sous_titre  = NULL,
  file_out    = NULL,
  width       = 29.7 / 2.54,
  height      = 21 / 2.54,
  dpi         = 300,
  n_last      = 12,
  exclure_typologies = c("Incorrecte")    # <-- [NOUVEAU]
){
  require(DBI); require(glue); require(dplyr); require(cowplot)

 
  # 1) Validation station / CPP
 
  is_station <- !is.null(station)

  if (is_station) {
    filtre_sql <- "s.code_station = $1"
    # join_sql dépend de tbl_sta → défini plus bas (après schema sanitize)
    param1     <- station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    join_sql   <- ""   # CPP orphelin
    param1     <- code_point_prelevement_aspe
  } else {
    stop("Veuillez fournir `station` OU `code_point_prelevement_aspe`.")
  }

 
  # 2) Connexion PG
 
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_sta     <- sprintf('"%s".aspe_stations',    schema_safe)
  tbl_ops     <- sprintf('"%s".aspe_operations',  schema_safe)

  # Maintenant qu'on connaît tbl_sta & tbl_ops, on reconstruit le JOIN
  if (is_station) {
    join_sql <- glue("JOIN {tbl_sta} s 
                      ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
  }

 
  # 3) Récupération des métadonnées : titre & sous-titre auto
 
  if (is_station) {
    meta_sql <- glue("
      SELECT code_station, libelle_station,
             code_point_prelevement_wama, libelle_point_prelevement_wama
      FROM {tbl_sta} s
      WHERE s.code_station = $1
      LIMIT 1;
    ")
    meta <- DBI::dbGetQuery(con, meta_sql, params = list(param1))
  } else {
    meta_sql <- glue("
      SELECT code_station, libelle_station,
             code_point_prelevement_wama, libelle_point_prelevement_wama
      FROM {tbl_sta} s
      WHERE s.code_point_prelevement_aspe = $1
      LIMIT 1;
    ")
    meta <- DBI::dbGetQuery(con, meta_sql, params = list(param1))
  }

  if (nrow(meta) == 1 && !is.na(meta$code_station) && nzchar(meta$code_station)) {
    titre_auto <- paste0(meta$code_station, " — ", meta$libelle_station)
  } else if (nrow(meta) == 1) {
    titre_auto <- paste0(meta$code_point_prelevement_wama, " — ", meta$libelle_point_prelevement_wama)
  } else {
    titre_auto <- param1
  }

  if (is.null(titre)) {
    titre <- glue("{titre_auto} — Synthèse habitats")
  }
  if (is.null(sous_titre)) {
    sous_titre <- glue("Synthèse réalisée le {format(Sys.Date(), '%d/%m/%Y')} par Eaux & Vilaine")
  }

 
  # 4) Sous-graphes — AVEC FILTRE TYPOLOGIES PROPAGÉ
 

  graph_habitats <- plot_habitat_heatmap(
    yaml_path    = yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut  = annee_debut,
    annee_fin    = annee_fin,
    n_last       = n_last,
    titre        = "Habitats et caractéristiques station",
    sous_titre   = "",
    schema       = schema_safe,
    exclure_typologies = exclure_typologies   # <-- [NOUVEAU]
  )

  graph_facies <- plot_facies_importance(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last,
    schema      = schema_safe,
    exclure_typologies = exclure_typologies    # <-- [NOUVEAU]
  )

  graph_profond <- plot_profondeur_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last,
    schema      = schema_safe,
    exclure_typologies = exclure_typologies    # <-- [NOUVEAU]
  )

  graph_surface <- plot_surface_pechee_histogram(
    yaml_path,
    code_station = station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    annee_debut = annee_debut,
    annee_fin   = annee_fin,
    n_last      = n_last,
    schema      = schema_safe,
    exclure_typologies = exclure_typologies    # <-- [NOUVEAU]
  )

 
  # 5) Si tous NULL → stop
 
  if (all(vapply(list(graph_habitats, graph_facies, graph_profond, graph_surface),
                 is.null, logical(1)))) {
    return(NULL)
  }

 
  # 6) Composition graphique cowplot
 
  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title = titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title    = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = ggplot2::element_text(size = 11, hjust = 0.5)
    )

  block_droit <- cowplot::plot_grid(
    graph_facies, graph_profond, graph_surface,
    nrow = 3
  )

  block_graphs <- cowplot::plot_grid(
    graph_habitats, block_droit,
    nrow = 1, rel_widths = c(3, 1)
  )

  planche <- cowplot::plot_grid(
    title_gg,
    block_graphs,
    nrow = 2, rel_heights = c(0.4, 3)
  )

 
  # 7) Export PNG optionnel
 
  if (!is.null(file_out)) {
    cowplot::save_plot(
      file_out, planche,
      base_width = width, base_height = height,
      dpi = dpi, bg = "white"
    )
  }

  return(planche)
}
