# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Planche IPR — Synthèse des n dernières opérations d'une station
#'
#' @description
#' Génère une planche de graphiques représentant les **n dernières opérations IPR**
#' réalisées sur une station donnée.  
#'
#' Chaque vignette est produite par `ipr_heatmap_3x3()` avec :
#' - conservation des **valeurs d’axes** dans chaque tuile (C1/C2/C3 ; L1/L2/L3),
#' - **masquage des titres** d’axes pour permettre une mise en page propre,
#' - ajout d’un **titre individuel** correspondant à la date de l’opération
#'   (format `jj/mm/aa`).
#'
#' Les vignettes sont ordonnées du **plus ancien au plus récent**, disposées
#' **de gauche à droite**, puis **de haut en bas**.  
#' La planche comporte des **titres d’axes X et Y mutualisés**, ce qui évite la
#' redondance tout en conservant la lisibilité des valeurs d’axes dans chaque
#' graphique individuel.
#'
#' @param yaml_path Chemin du fichier YAML contenant les paramètres
#'   de connexion PostgreSQL.
#' @param station Code Sandre de la station (`code_station`) pour laquelle
#'   la planche doit être générée.
#' @param annee_debut Année minimale prise en compte.  
#'   Par défaut : `1950`.
#' @param annee_fin Année maximale prise en compte.  
#'   Par défaut : année courante.
#' @param schema Nom du schéma PostgreSQL contenant les tables ASPE.
#'   Par défaut : `"qe"`.
#' @param titre Titre principal de la planche.  
#'   Par défaut : NULL.
#' @param sous_titre Sous titre de la planche.  
#'   Par défaut : NULL.
#' @param file_out Chemin d’enregistrement (PNG).  
#'   Si `NULL`, aucun fichier n’est enregistré.
#' @param width Largeur de la figure en pouces.  
#'   Par défaut : format A4 paysage (`29.7/2.54`).
#' @param height Hauteur de la figure en pouces.  
#'   Par défaut : A4 paysage (`21/2.54`).
#' @param dpi Résolution de sortie PNG. Par défaut `300`.
#' @param n_last Nombre maximal d’opérations affichées.  
#'   Par défaut : `12`.
#' @param affiche_guildes_eco affiche les différentes guildes écologiques en bas de page (défaut = TRUE)
#' @param ... Arguments supplémentaires transmis à `ipr_heatmap_3x3()`
#'   (permet par exemple d’ajuster dynamiquement les tailles de police).
#'
#' @return Un objet `ggplot`/grob (assemblage cowplot) représentant la planche.
#'   Retourne `NULL` si aucune opération IPR n’est trouvée pour la station.
#'
#' @details
#' La fonction réalise les étapes suivantes :
#'
#' 1. Connexion à PostgreSQL via les paramètres du fichier YAML.
#' 2. Extraction des opérations IPR correspondant à `station` depuis  
#'    `schema.aspe_ipr_compl`, jointes à `schema.aspe_operations` pour récupérer
#'    la date de prélèvement.
#' 3. Filtrage selon `annee_debut` et `annee_fin`.
#' 4. Sélection des `n_last` opérations les plus récentes, suivie d’un tri
#'    **chronologique** du plus ancien au plus récent (ordre d’affichage).
#' 5. Génération, pour chaque opération, d’une vignette via `ipr_heatmap_3x3()`
#'    avec :
#'    - **show_axis_text = TRUE** (conserve les valeurs d’axes),
#'    - **show_axis_titles = FALSE** (titres mutualisés ensuite),
#'    - titre de sous-graphe = date de l’opération.
#' 6. Construction d’une grille de vignettes (4 colonnes × 3 lignes max).
#' 7. Ajout d’un **titre général**, d’un **axe X commun** et d’un **axe Y commun**.
#' 8. Export éventuel en PNG via `cowplot::save_plot()`.
#'
#' @examples
#' \dontrun{
#' make_analyse_pop_IPR_planche(
#'   yaml_path = "C:/workspace/gwilenalim/yaml/config.yml",
#'   station   = "04216050",
#'   annee_debut = 2000,
#'   n_last    = 12,
#'   file_out  = "ipr_planche_04216050.png"
#' )
#' }
#'
#' @export
make_analyse_pop_IPR_planche <- function(
  yaml_path,
  station,
  annee_debut = 1950,
  annee_fin   = as.numeric(format(Sys.Date(), "%Y")),
  schema      = "qe",
  titre       = NULL,
  sous_titre=NULL,
  file_out    = NULL,
  width = 29.7/2.54,
  height = 21/2.54,
  dpi = 300,
  n_last = 12,
  affiche_guildes_eco=TRUE
){
  `%||%` <- function(x,y) if (!is.null(x)) x else y

  # titres automatiques
  con <- connect_pg(yaml_path)
on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)


info_titres <- .aspe_fetch_meta_and_titles(
  con = con,
  schema = schema %||% "qe",
  station = station,
  code_point_prelevement_aspe = NULL,  # analyse IPR = station-based
  default_title_suffix = " — Effectifs pêchés vs attendus (IPR)",
  default_subtitle_prefix = "Synthèse réalisée le "
)

if (is.null(titre)) {
  titre <- info_titres$titre_auto
}
if (is.null(sous_titre)) {
  sous_titre <- info_titres$sous_titre_auto
}


  # --- Récupération opérations IPR
  sql <- sprintf("
    SELECT c.code_operation, o.date_operation
    FROM %s.aspe_ipr_compl c
    JOIN %s.aspe_operations o
      ON c.code_operation = o.code_operation
    WHERE c.code_station = $1;
  ", schema, schema)

  ops <- DBI::dbGetQuery(con, sql, params=list(station))
  if (!nrow(ops)) return(NULL)

  # --- Parse date
  parse_iso <- function(x){
    x2 <- gsub("Z$","+00:00",x)
    out <- suppressWarnings(as.POSIXct(x2, format="%Y-%m-%dT%H:%M:%OS%z"))
    idx <- is.na(out)
    if (any(idx))
      out[idx] <- suppressWarnings(as.POSIXct(x[idx], format="%Y-%m-%d"))
    out
  }

  ops$dt <- parse_iso(ops$date_operation)
  ops$annee <- as.integer(format(ops$dt,"%Y"))
  ops <- ops[ops$annee>=annee_debut & ops$annee<=annee_fin, ]
  if (!nrow(ops)) return(NULL)

  ops <- ops[order(ops$dt, decreasing=TRUE), ]
  ops <- ops[seq_len(min(n_last, nrow(ops))), ]
  ops <- ops[order(ops$dt), ]

  fmt_date <- function(x) format(x,"%d/%m/%y")
  plots <- vector("list", nrow(ops))

  # --- Génération vignettes
  for (i in seq_len(nrow(ops))) {
    code_op <- ops$code_operation[i]
    dt_lab  <- fmt_date(ops$dt[i])

    p <- try(
      ipr_heatmap_3x3(
        yaml_path=yaml_path,
        code_operation=code_op,
        titre=NULL,
        size_labels=2.8,
        lineheight_labels=0.85,
        size_axis_text=7,
        size_axis_title=8,
        tile_border_size=0.6,
        show_axis_text   = TRUE,   # <-- valeurs d’axes conservées
        show_axis_titles = FALSE   # <-- titres supprimés (mutualisés plus tard)
      ),
      silent=TRUE
    )

    if (!inherits(p,"try-error")) {
      p <- p + ggplot2::ggtitle(dt_lab) +
        ggplot2::theme(plot.title=ggplot2::element_text(size=9, face="bold"))
    } else {
      p <- ggplot2::ggplot() +
        ggplot2::geom_text(aes(0,0,label=paste0("Erreur ", code_op))) +
        ggplot2::theme_void()
    }

    plots[[i]] <- p
  }

  # --- Axes mutualisés
  xlab_common <- ggplot2::ggplot() +
    ggplot2::labs(x="Effectif capturé") +
    ggplot2::theme_void() +
    ggplot2::theme(axis.title.x=ggplot2::element_text(size=12, face="bold"))

  ylab_common <- ggplot2::ggplot() +
    ggplot2::labs(y="Probabilité selon IPR") +
    ggplot2::theme_void() +
    ggplot2::theme(axis.title.y=ggplot2::element_text(size=12, face="bold", angle=90))

  # --- Grille
  grid_plots <- cowplot::plot_grid(plotlist=plots, ncol=4)

  grid_with_y <- cowplot::plot_grid(
    ylab_common, grid_plots,
    ncol=2, rel_widths=c(0.04,1)
  )

  grid_with_xy <- cowplot::plot_grid(
    grid_with_y, xlab_common,
    nrow=2, rel_heights=c(1,0.07)
  )

  # --- Titre général
  title_gg <- ggplot2::ggplot() +
    ggplot2::labs(title=titre, subtitle = sous_titre) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title=ggplot2::element_text(size=16, face="bold", hjust=0.5)
    )

  planche <- cowplot::plot_grid(
    title_gg, grid_with_xy,
    nrow=2, rel_heights=c(0.15,1)
  )

  if(affiche_guildes_eco){
      planche <- cowplot::plot_grid(
    planche, graph_modalites_ipr(text_size = 3),
    nrow=2, rel_heights=c(20,2.5)
  )
    
  }
  
  
  
  # --- Export
  if (!is.null(file_out)) {
    cowplot::save_plot(
      file_out, planche,
      base_width=width, base_height=height,
      dpi=dpi, bg="white"
    )
  }

  return(planche)
}
