# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Renvoie les noms vernaculaires associés à des codes taxons ASPE
#'
#' Cette fonction permet d'associer à chaque code taxon ASPE son nom
#' vernaculaire correspondant.  
#' Elle utilise une table de correspondance codée en dur, constituée :
#' \itemize{
#'   \item de la liste \code{NOMS} fournie par l'utilisateur ;
#'   \item des noms vernaculaires issus de la table officielle des espèces
#'   (extrait du document fourni contenant l'ensemble des codes ASPE).
#' }
#'
#' Lorsque plusieurs sources fournissent un nom pour un même code, la
#' correspondance provenant de la table utilisateur \code{NOMS} est considérée
#' prioritaire.  
#' Si un code taxon ne figure dans aucune table, la fonction renvoie
#' simplement le code d'origine.
#'
#' @param codes Un vecteur de caractères contenant des codes ASPE (ex. `"ABL"`,
#' `"VAB"`, `"TRF"`, `"ANG"`).
#'
#' @return Un vecteur de même longueur que \code{codes}, contenant les noms
#' vernaculaires correspondants.  
#' Pour les codes non reconnus, la valeur retournée est le code fourni.
#'
#' @details
#' La table de correspondance inclut l'ensemble des taxons présents :
#' \itemize{
#'   \item dans la table utilisateur (ex. : \code{"ABL"} → \code{"Ablette"},
#'   \code{"BRX"} → \code{"Brème sp."}, etc.) ;
#'   \item dans le document de référence joint (ex. : \code{"APR"} →
#'   \code{"Apron du Rhône"}, \code{"OBL"} → \code{"Omble chevalier"},
#'   \code{"CPV"} → \code{"Cyprinodonte de Valence"}, etc.).
#' }
#'
#' Ce mécanisme permet d'assurer la cohérence entre les codes ASPE bruts
#' et les regroupements éventuels effectués en amont (ex. néotaxons d'IPR).
#'
#' @examples
#' nom_vernaculaire_aspe(c("ABL", "VAB", "TRF", "XXX", "ANG", "CPV"))
#' # Résultat :
#' # [1] "Ablette"        "Vairon béarnais" "Truite fario"
#' # [4] "XXX"            "Anguille"       "Cyprinodonte de Valence"
#'
#' @export
nom_vernaculaire_aspe <- function(codes) {
  
  # Table NOMS fournie par l'utilisateur
  base_noms <- c(
    "ABL"="Ablette","ANG"="Anguille","BAF"="Barbeau",
    "BAM"="Barbeau mér.","BLN"="Blageon","BOU"="Bouvière",
    "BRX"="Brème sp.","CAX"="Carassin","CCO"="Carpe",
    "CHX"="Chabot","EPI"="Epinoche","ESX"="Brochet",
    "GAR"="Gardon","GOX"="Goujon","GRE"="Grémille",
    "HOT"="Hotu","LOX"="Loche sp.","LOT"="Lote",
    "LPX"="Lamproie sp.","OBX"="Ombre","PCH"="Poisson chat",
    "PER"="Perche","PES"="Perche soleil","PHX"="Vairon",
    "PUX"="Epinochette","ROT"="Rotengle","SAN"="Sandre",
    "SAT"="Saumon","SPI"="Spirlin","SQX"="Chevesne",
    "TAN"="Tanche","TOX"="Toxostome","TRF"="Truite fario",
    "VAX"="Vandoise"
  )
  
  # Extraction du PDF (codes aspe + noms vernaculaires)
  noms_pdf <- c(
    "EST"="Esturgeon européen",
    "ANG"="Anguille européenne",
    "ATB"="Athérine",
    "BLE"="Blennie fluviatile",
    "BBG"="Black-Bass",
    "CDR"="Crapet de roche",
    "PES"="Perche-soleil",   # déjà dans base_noms
    "ALA"="Grande Alose",
    "ALF"="Alose feinte",
    "LOE"="Loche d'étang",
    "LOR"="Loche épineuse",
    "COR"="Corégone (lavaret)",
    "CHA"="Chabot",
    "ABH"="Able de Heckel",
    "ABL"="Ablette",
    "ASP"="Aspe",
    "BAF"="Barbeau fluviatile",
    "BAM"="Barbeau méridional",
    "BLN"="Blageon",
    "BOU"="Bouvière",
    "BRB"="Brème bordelière",
    "BRE"="Brème commune",
    "CAA"="Carassin doré",
    "CAG"="Carassin argenté",
    "CAR"="Carpe argentée",
    "CAS"="Carassin commun",
    "CCO"="Carpe commune",
    "CCU"="Carpe cuir",
    "CMI"="Carpe miroir",
    "CGT"="Carpe à grosse tête",
    "CHE"="Chevaine",
    "CTI"="Carpe Amour",
    "GAR"="Gardon",
    "GOU"="Goujon",
    "HOT"="Hotu",
    "IDE"="Ide mélanote",
    "PIM"="Tête de boule",
    "PSR"="Pseudorasbora",
    "ROT"="Rotengle",
    "SPI"="Spirlin",
    "TAN"="Tanche",
    "TOX"="Toxostome",
    "VAB"="Vairon béarnais",
    "VAC"="Vairon catalan",
    "VAI"="Vairon",
    "VAN"="Vandoise",
    "VAR"="Vandoise rostrée",
    "VIM"="Vimbe",
    "APC"="Aphanius de Corse",
    "APE"="Aphanius d'Espagne",
    "BRO"="Brochet",
    "EPI"="Epinoche",
    "EPT"="Epinochette",
    "GOB"="Gobie buhotte",
    "PCH"="Poisson-chat",
    "LOT"="Lote",
    "LOF"="Loche franche",
    "EPE"="Eperlan",
    "APR"="Apron du Rhône",
    "GRE"="Grémille",
    "PER"="Perche",
    "SAN"="Sandre",
    "LPM"="Lamproie marine",
    "LPP"="Lamproie de Planer",
    "LPR"="Lamproie fluviatile",
    "GAM"="Gambusie",
    "HUC"="Huchon",
    "OBL"="Omble chevalier",
    "SAT"="Saumon atlantique",
    "SCO"="Saumon coho",
    "SDF"="Saumon de fontaine",
    "TAC"="Truite arc‑en‑ciel",
    "TRC"="Truite à grosses taches (Corse)",
    "TRF"="Truite fario",
    "TRL"="Truite de lac",
    "TRM"="Truite de mer",
    "CRI"="Cristivomer",
    "SIL"="Silure",
    "OBR"="Ombre commun",
    "UMB"="Umbre pygmée",
    "CPV"="Cyprinodonte de Valence"
  )
  
  # Fusion, priorité aux noms définis par l'utilisateur
  TABLE <- c(base_noms, noms_pdf[setdiff(names(noms_pdf), names(base_noms))])
  
  # Mapping
  out <- TABLE[codes]
  out[is.na(out)] <- codes[is.na(out)]
  
  return(out)
}

