# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des puissances de pêche ASPE pour une station ou un CPP
#'
#' Extrait les puissances de pêche (`puissance`) depuis la table
#' `aspe_operations`, filtrées selon :
#' - une station (`code_station`) **ou** un point ASPE (`code_point_prelevement_aspe`) ;
#' - un intervalle d'années (`annee_debut` – `annee_fin`) ;
#' - un filtre d'exclusion de typologies d'opérations via
#'   `libelle_qualification_operation` (`exclure_typologies`) ;
#' - les `n_last` dernières dates distinctes.
#'
#' Produit un histogramme ggplot2 où chaque barre représente la **puissance (kVA)**.
#' Les dates sont affichées en ordre chronologique (format `%d/%m/%y`), pivotées
#' de 90° pour lisibilité.
#'
#' @param yaml_path Chemin vers le fichier YAML de connexion PostgreSQL.
#' @param code_station Code Sandre de la station (prioritaire si fourni).
#' @param code_point_prelevement_aspe Code du point ASPE utilisé si `code_station` est `NULL`.
#' @param annee_debut Année minimale (défaut : 1950).
#' @param annee_fin Année maximale (défaut : année courante).
#' @param n_last Nombre de dernières dates distinctes à afficher (défaut : 10).
#' @param titre Titre du graphique (défaut : `"Puissance (kVA)"`).
#' @param schema Schéma SQL contenant les tables (défaut `"qe"`).
#' @param exclure_typologies Vecteur des typologies d'opération à exclure
#'   (défaut : `"Incorrecte"`).
#'
#' @return Un ggplot2 ou `NULL` si aucune donnée.
#' @export
plot_puissance_pechee_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Puissance (kVA)",
  schema      = "qe",
  exclure_typologies = c("Incorrecte")  # <-- [NOUVEAU]
){
  library(DBI); library(dplyr); library(ggplot2)
  library(lubridate); library(glue)

  
  # 1) Validation paramètres
  
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("Les deux paramètres sont fournis : priorité au code_station.")
  }
  use_station <- !is.null(code_station)

  
  # 2) Connexion
  
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations', schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',   schema_safe)

  
  # 3) Logique station / CPP
  
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s 
                        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else {
    join_sql   <- ""     # CPP → aucun JOIN
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  
  # 4) SQL sécurisé + EXCLUSION TYPOLOGIES
  
  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.puissance::float     AS puissance
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND EXTRACT(YEAR FROM o.date_operation::date) BETWEEN $2 AND $3
      AND o.puissance IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin) 
  )

  if (nrow(df) == 0) {
    message("Aucune puissance disponible pour les critères fournis.")
    return(NULL)
  }

  
  # 5) Filtrer les n dernières dates distinctes
  
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(format(df$date_op, "%d/%m/%y"),
                          levels = format(df$date_op, "%d/%m/%y"))

  
  # 6) Graphique
  
  ggplot(df, aes(x = date_label, y = puissance)) +
    geom_col(fill = "grey30") +
    labs(title = titre, x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}

