# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des profondeurs par faciès (ASPE)
#'
#' Cette fonction extrait les profondeurs moyennes de faciès
#' (`facies_profondeur_moyenne`) et les types de faciès (`facies_libelle_type`)
#' depuis `aspe_operations`, pour une station ou un point ASPE.
#'
#' Elle nettoie les chaînes (retrait du préfixe "\\x", découpages, normalisation
#' des noms de faciès) puis met en correspondance profondeurs et faciès.
#'
#' Le filtrage tient compte :
#' - du code station ou CPP,
#' - d’un intervalle d’années,
#' - des `n_last` dernières opérations distinctes,
#' - des typologies d’opérations à exclure (`libelle_qualification_operation`).
#'
#' Le résultat est un histogramme où chaque date affiche une ou plusieurs barres
#' (position dodge), avec une couleur par type de faciès.
#'
#' @param yaml_path Chemin YAML de connexion PG
#' @param code_station Code Sandre (prioritaire si fourni)
#' @param code_point_prelevement_aspe Code ASPE si pas de station
#' @param annee_debut Année minimale (défaut 1950)
#' @param annee_fin Année maximale (défaut = année courante)
#' @param n_last Nombre de dernières dates distinctes (défaut 10)
#' @param titre Titre du graphique
#' @param schema Schéma SQL (défaut "qe")
#' @param exclure_typologies Vecteur des typologies d’opérations à exclure
#'
#' @return Un ggplot2 ou NULL
#' @export
plot_facies_profondeur_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin = as.integer(format(Sys.Date(), "%Y")),
  n_last = 10,
  titre = "Profondeurs par faciès",
  schema = "qe",
  exclure_typologies = c("Incorrecte")
){
  library(DBI); library(dplyr); library(ggplot2)
  library(stringr); library(tidyr); library(glue)

  # Helpers compatibles fusen
  clean_depths <- function(x) {
    x2 <- str_remove(x, "^\\\\x")
    x2 <- str_squish(x2)
    vals <- str_split(x2, "\\s+")[[1]]
    suppressWarnings(as.numeric(vals))
  }

  clean_facies <- function(x) {
    x2 <- str_remove(x, "^\\\\x")
    x2 <- str_squish(x2)
    x2 <- str_replace_all(x2, " ", "")
    fac <- str_split(x2, "(?=[A-Z])")[[1]]
    fac <- fac[fac != "" & !is.na(fac)]
    ifelse(grepl("^Profond", fac, ignore.case = TRUE), "Profond", fac)
  }

  expand_match <- function(date_op, date_label, depths, facies){
    nd <- length(depths); nf <- length(facies)
    if (nd == nf) {
      tibble(date_op=date_op, date_label=date_label, profondeur=depths, facies=facies)
    } else if (nd > nf) {
      tibble(date_op=date_op, date_label=date_label,
             profondeur=depths,
             facies=rep(facies, length.out=nd))
    } else {
      tibble(date_op=date_op, date_label=date_label,
             profondeur=rep(depths, length.out=nf),
             facies=facies)
    }
  }

  # Connexion PG
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations',  schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',    schema_safe)

  if (!is.null(code_station)) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    join_sql   <- ""
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  } else {
    stop("Veuillez fournir code_station OU code_point_prelevement_aspe.")
  }

  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.facies_profondeur_moyenne,
      o.facies_libelle_type
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
      AND NOT (o.libelle_qualification_operation = ANY($4))
      AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN $2 AND $3
      AND o.facies_profondeur_moyenne IS NOT NULL
      AND o.facies_libelle_type IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con, sql,
    params=list(param1, annee_debut, annee_fin, exclure_typologies)
  )
  if (nrow(df) == 0) return(NULL)

  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- format(df$date_op, "%d/%m/%y")

  df$depths_list  <- lapply(df$facies_profondeur_moyenne, clean_depths)
  df$facies_list  <- lapply(df$facies_libelle_type,       clean_facies)

  # Expansion SANS pipe et SANS mutate(list(...))
  long_df <- bind_rows(
    lapply(seq_len(nrow(df)), function(i){
      expand_match(
        df$date_op[i],
        df$date_label[i],
        df$depths_list[[i]],
        df$facies_list[[i]]
      )
    })
  )

  facies_colors <- c(
    "Courant" = "#6D76F8",
    "Plat"    = "#7FDD4C",
    "Profond" = "#C72C48"
  )

  ggplot(long_df, aes(x = factor(date_label), y = profondeur, fill = facies)) +
    geom_col(position = position_dodge(width = 0.8)) +
    scale_fill_manual(values = facies_colors, drop = FALSE) +
    labs(
      title = titre,
      x = "",
      y = "Profondeur (m)",
      fill = "Faciès"
    ) +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}

