# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des profondeurs par faciès (ASPE)
#'
#' NE FONCTIONNE PAS BUG HUBEAU
#'
#' Nettoie et transforme les champs `facies_profondeur_moyenne` et
#' `facies_libelle_type` issus de `aspe_operations`, puis produit un
#' histogramme des profondeurs moyennes par faciès.
#'
#' Fonction compatible station ou CPP :
#' - Si `code_station` et `code_point_prelevement_aspe` sont fournis,
#'   `code_station` est prioritaire.
#' - En mode CPP : **aucun JOIN** avec `aspe_stations`.
#'
#' Cette version applique aussi un filtrage optionnel des typologies
#' d’opérations via `libelle_qualification_operation`.
#'
#' @param yaml_path Chemin YAML de connexion PostgreSQL.
#' @param code_station Code Sandre de la station.
#' @param code_point_prelevement_aspe Code ASPE si pas de station.
#' @param annee_debut Année minimale (défaut 1950).
#' @param annee_fin Année maximale (défaut = année courante).
#' @param n_last Nombre de dates distinctes à conserver.
#' @param titre Titre du graphique.
#' @param schema Schéma SQL (défaut `"qe"`).
#' @param exclure_typologies Typologies d’opérations à exclure
#'        (défaut `"Incorrecte"`).
#'
#' @return Un ggplot2 ou `NULL`
#' @export
plot_facies_profondeur_histogram_provisoire <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Profondeurs par faciès",
  schema      = "qe",
  exclure_typologies = c("Incorrecte")     # <-- [NOUVEAU PARAMÈTRE]
){
  library(DBI); library(dplyr); library(ggplot2)
  library(stringr); library(tidyr); library(glue)

  
  # 1) Validation station / CPP
  
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("Les deux paramètres sont fournis. Priorité au code_station.")
  }
  use_station <- !is.null(code_station)

  
  # 2) Connexion & chemins tables
  
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations',  schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',    schema_safe)

  
  # 3) SQL sécurisé + EXCLUSION TYPOLOGIES
  
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s
                        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1 <- code_station
  } else {
    join_sql   <- ""  # CPP = no join
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1 <- code_point_prelevement_aspe
  }

  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.facies_profondeur_moyenne,
      o.facies_libelle_type
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN $2 AND $3
      AND o.facies_profondeur_moyenne IS NOT NULL
      AND o.facies_libelle_type IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin) 
  )
  if (nrow(df) == 0) return(NULL)

  
  # 4) Sélection n dernières dates
  
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(
    format(df$date_op, "%d/%m/%y"),
    levels = format(df$date_op, "%d/%m/%y")
  )

  
  # 5) Nettoyage facies_profondeur_moyenne
  
  df <- df %>%
    mutate(
      facies_profondeur_moyenne = str_remove(facies_profondeur_moyenne, "^\\\\x"),
      facies_profondeur_moyenne = str_squish(facies_profondeur_moyenne),
      depths_list = str_split(facies_profondeur_moyenne, "\\s+"),
      depths_list = lapply(depths_list, function(v) suppressWarnings(as.numeric(v)))
    )

  
  # 6) Nettoyage facies_libelle_type
  
  df <- df %>%
    mutate(
      facies_raw = str_remove(facies_libelle_type, "^\\\\x"),
      facies_raw = str_squish(facies_raw),
      facies_raw = str_replace_all(facies_raw, " ", ""),
      facies_raw = str_split(facies_raw, "(?=[A-Z])"),
      facies_raw = lapply(facies_raw, function(v) {
        v <- v[v != "" & !is.na(v)]
        ifelse(grepl("^Profond", v, ignore.case = TRUE), "Profond", v)
      })
    )

  
  # 7) Mise en correspondance profondeurs ↔ faciès
  
library(purrr)

df <- df %>%
  mutate(
    match_lists = map2(depths_list, facies_raw, ~{
      d  <- .x; f  <- .y
      nd <- length(d); nf <- length(f)
      if (nd == nf) {
        tibble(profondeur = d, facies = f)
      } else if (nd > nf) {
        tibble(profondeur = d, facies = rep(f, length.out = nd))
      } else {
        tibble(profondeur = rep(d, length.out = nf), facies = f)
      }
    })
  ) %>%
  select(date_op, date_label, match_lists) %>%
  unnest(match_lists)

  
  # 8) Couleurs faciès
  
  facies_colors <- c(
    "Courant" = "#6D76F8",
    "Plat"    = "#7FDD4C",
    "Profond" = "#C72C48"
  )

  
  # 9) Graphique final
  
  ggplot(df, aes(x = date_label, y = profondeur, fill = facies)) +
    geom_col(position = position_dodge(width = 0.8)) +
    scale_fill_manual(values = facies_colors, drop = FALSE) +
    labs(
      title = titre,
      x = "",
      y = "Profondeur (m)",
      fill = "Faciès"
    ) +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x  = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title   = element_text(face = "bold")
    )
}

