# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des longueurs pêchées ASPE pour une station ou un CPP
#'
#' Extrait les longueurs pêchées (`longueur`) depuis la table
#' `aspe_operations`, filtrées selon :
#' - une station (`code_station`) **ou** un point ASPE (`code_point_prelevement_aspe`) ;
#' - un intervalle d'années (`annee_debut` – `annee_fin`) ;
#' - un filtre d'exclusion de typologies d'opérations via
#'   `libelle_qualification_operation` (`exclure_typologies`) ;
#' - les `n_last` dernières dates distinctes.
#'
#' Produit un histogramme ggplot2 où chaque barre représente la **longueur** (en m)
#' relevée lors d'une opération ; les dates sont affichées en **ordre chronologique**
#' (format `%d/%m/%y`) et pivotées de 90°.
#'
#' @param yaml_path Chemin vers le fichier YAML de connexion PostgreSQL.
#' @param code_station \[`character(1)`\]\  
#'   Code Sandre de la station. Si renseigné conjointement avec
#'   `code_point_prelevement_aspe`, il est **prioritaire** (un warning est émis).
#' @param code_point_prelevement_aspe \[`character(1)`\]\  
#'   Code du point de prélèvement ASPE utilisé si `code_station` n'est pas fourni.
#' @param annee_debut \[`numeric(1)`\]\  
#'   Année minimale des opérations à prendre en compte (défaut : 1950).
#' @param annee_fin \[`numeric(1)`\]\  
#'   Année maximale (défaut : année courante).
#' @param n_last \[`integer(1)`\]\  
#'   Nombre des **dernières dates d’opérations distinctes** à représenter (défaut : 10).
#' @param titre \[`character(1)`\]\  
#'   Titre du graphique (défaut : `"Longueur station (m)"`).
#' @param schema Schéma SQL contenant les tables (défaut `"qe"`).
#' @param exclure_typologies Vecteur des **typologies d'opération à exclure**
#'   (défaut : `"Incorrecte"`), appliqué à `aspe_operations.libelle_qualification_operation`.
#'
#' @return Un objet `ggplot2` ou `NULL` si aucune donnée.
#'
#' @examples
#' \dontrun{
#' # Par station, exclusion par défaut ("Incorrecte")
#' plot_longueur_pechee_histogram(
#'   yaml_path = "config/connexion.yml",
#'   code_station = "04216050",
#'   annee_debut  = 2000,
#'   annee_fin    = 2025,
#'   n_last       = 12
#' )
#'
#' # Par CPP, avec plusieurs typologies exclues
#' plot_longueur_pechee_histogram(
#'   yaml_path = "config/connexion.yml",
#'   code_point_prelevement_aspe = "CPP_123",
#'   annee_debut = 2010,
#'   exclure_typologies = c("Incorrecte","Doublon","Hors périmètre")
#' )
#' }
#'
#' @export
plot_longueur_pechee_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Longueur station (m)",
  schema      = "qe",
  exclure_typologies = c("Incorrecte")
){
  # Imports
  library(DBI); library(dplyr); library(ggplot2); library(lubridate); library(glue)

  
  # 1) Validation des paramètres
  
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("Les deux paramètres sont fournis : priorité au code_station.")
  }
  use_station <- !is.null(code_station)

  
  # 2) Connexion & tables
  
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations', schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',   schema_safe)

  
  # 3) Logique Station / CPP — (CPP = pas de JOIN)
  
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else {
    join_sql   <- ""  # CPP orphelin -> aucun JOIN
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  
  # 4) SQL sécurisé + exclusion typologies 
  
  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.longueur::float      AS longueur
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND EXTRACT(YEAR FROM o.date_operation::date) BETWEEN $2 AND $3
      AND o.longueur IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin)
  )

  if (nrow(df) == 0) {
    message("Aucune longueur disponible pour les critères fournis.")
    return(NULL)
  }

  
  # 5) n dernières dates distinctes
  
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(
    format(df$date_op, "%d/%m/%y"),
    levels = format(df$date_op, "%d/%m/%y")
  )

  
  # 6) Graphique
  
  ggplot(df, aes(x = date_label, y = longueur)) +
    geom_col(fill = "grey30") +
    labs(title = titre, x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}
