# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Heatmap des conditions / habitats (présences, abondances, hydrologie)
#'
#' @param yaml_path Chemin YAML (connexion PG)
#' @param code_station Code Sandre de la station (ou NULL si `code_point_prelevement_aspe` fourni)
#' @param code_point_prelevement_aspe Code du point ASPE (ou NULL si `code_station` fourni)
#' @param annee_debut Année de début (défaut 1950)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param n_last Nombre d'opérations affichées (dates distinctes)
#' @param show_nulle_abondance Afficher la classe "Nulle" pour l'abondance
#' @param dot_size Taille des points
#' @param dot_stroke Épaisseur du trait
#' @param abond_colors Couleurs des classes d'abondance
#' @param hydro_colors Couleurs des classes hydrologiques
#'
#' @return Un objet `ggplot2` (ou `NULL` si aucune donnée)
#'
#' @examples
#' \dontrun{
#' plot_habitat_heatmap(".../config.yml", code_station = "04216050", annee_debut = 2000)
#' }
#' @export
#' @noRd  
plot_habitat_heatmap <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = lubridate::year(Sys.Date()),
  n_last = 12,
  show_nulle_abondance = FALSE,
  dot_size = 6,
  dot_stroke = 0.6,
  abond_colors = c(Faible = "#CCFF99", Moyen = "#31a354", Fort = "#003300"),
  hydro_colors = c("Bas/Faible" = "#99FFFF", "Moyen/Stable" = "#0066CC", "Haut/Fort" = "#084594")
){
  y <- yaml::read_yaml(yaml_path)
  y$port        <- y$port        %||% 5432
  y$sslmode     <- y$sslmode     %||% "prefer"
  y$search_path <- y$search_path %||% "qe,public"

  con <- DBI::dbConnect(
    RPostgres::Postgres(),
    dbname = y$dbname, host = y$host, port = y$port,
    user = y$user, password = y$password,
    sslmode = y$sslmode,
    options = sprintf("-c search_path=%s", y$search_path)
  )
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  if (!is.null(code_station)) {
    filtre_sql <- "s.code_station = $1"
    param1 <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"
    param1 <- code_point_prelevement_aspe
  } else {
    stop("Fournir soit `code_station`, soit `code_point_prelevement_aspe`.", call. = FALSE)
  }

  vars_habitats <- c(
    "abondance_abri_vegetal_aquatique","abondance_abris_rocheux","abondance_embacles_souches",
    "abondance_sous_berges","abondance_trous_fosses","abondance_vegetation_aquatique",
    "abondance_vegetation_bordure","facies_libelle_granulo_dominante","facies_libelle_granulo_accessoire",
    "facies_vegetation_dominante","libelle_conditions_hydrologiques","libelle_granulo_donnees_env_dominante",
    "libelle_granulo_donnees_env_accessoire","libelle_intensite_ombrage","libelle_tendance_debit","libelle_turbidite",
    "presence_curage","presence_deboisement","presence_diversite_ecoulement","presence_extraction_granulats",
    "presence_faucardage","presence_modification_morphologique","presence_repeuplement","presence_ripisylve_equilibree",
    "presence_secteur_canalise","presence_secteur_debit_reserve","presence_secteur_eclusee","presence_secteur_navigue",
    "presence_secteur_soutien_etiage","presence_sports_nautiques"
  )

  cols <- c("date_operation", vars_habitats)
  sql <- sprintf("
    SELECT %s
    FROM qe.aspe_operations o
    JOIN qe.aspe_stations s
      ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe
    WHERE %s
      AND o.date_operation IS NOT NULL
      AND date_part('year', CAST(o.date_operation AS timestamp)) BETWEEN $2 AND $3
    ORDER BY CAST(o.date_operation AS timestamp);
  ", paste(sprintf("o.%s", cols), collapse = ", "), filtre_sql)

  df <- DBI::dbGetQuery(con, sql, params = list(param1, annee_debut, annee_fin))
  if (!nrow(df)) return(NULL)

  df <- df |>
    dplyr::mutate(
      date_time = suppressWarnings(lubridate::as_datetime(date_operation, tz = "UTC")),
      date      = as.Date(date_time)
    ) |>
    dplyr::filter(!is.na(date)) |>
    dplyr::arrange(date)

  if (!is.null(n_last) && is.finite(n_last) && n_last > 0) {
    last_dates <- df |> dplyr::distinct(date) |> dplyr::arrange(dplyr::desc(date)) |> dplyr::slice(1:n_last) |> dplyr::pull(date)
    df <- df |> dplyr::filter(date %in% last_dates) |> dplyr::arrange(date)
  }

  df <- df |>
    dplyr::mutate(
      date_label  = format(date, "%d/%m/%y"),
      date_factor = factor(date_label, levels = unique(date_label), ordered = TRUE)
    )

  vars_presentes <- vars_habitats[vars_habitats %in% names(df)]
  is_non_empty <- function(x) any(!is.na(x) & stringr::str_trim(as.character(x)) != "" & as.character(x) != "NA")
  vars_non_vides <- vars_presentes[vapply(df[vars_presentes], is_non_empty, logical(1))]
  if (!length(vars_non_vides)) {
    return(
      ggplot2::ggplot() +
        ggplot2::theme_minimal(base_size = 13) +
        ggplot2::labs(
          title = "Conditions / habitats — variables vides",
          subtitle = paste0(annee_debut, "–", annee_fin),
          caption = "Variables d'habitat présentes mais sans valeurs exploitables"
        )
    )
  }

  tidy_df <- df |>
    dplyr::select(date, date_factor, dplyr::all_of(vars_non_vides)) |>
    tidyr::pivot_longer(cols = dplyr::all_of(vars_non_vides), names_to = "variable", values_to = "valeur") |>
    dplyr::mutate(valeur = ifelse(is.na(valeur) | stringr::str_trim(as.character(valeur)) %in% c("", "NA"),
                                  NA_character_, as.character(valeur)))

  presence_df <- tidy_df |>
    dplyr::filter(stringr::str_starts(variable, "presence_")) |>
    dplyr::mutate(v = tolower(stringr::str_trim(valeur))) |>
    dplyr::mutate(val_presence = dplyr::case_when(
      v %in% c("oui","true","vrai","yes") ~ "Oui",
      v %in% c("non","false","faux","no") ~ "Non",
      TRUE ~ NA_character_
    )) |>
    dplyr::filter(!is.na(val_presence)) |>
    dplyr::mutate(val_presence = factor(val_presence, levels = c("Non","Oui")))

  abond_df <- tidy_df |>
    dplyr::filter(stringr::str_starts(variable, "abondance_")) |>
    dplyr::mutate(v = tolower(stringr::str_replace_all(stringr::str_trim(valeur), "[éèê]", "e"))) |>
    dplyr::mutate(class_abond = dplyr::case_when(
      stringr::str_detect(v, "faibl")             ~ "Faible",
      stringr::str_detect(v, "modere|moyen")      ~ "Moyen",
      stringr::str_detect(v, "fort|eleve|import") ~ "Fort",
      stringr::str_detect(v, "nul") & show_nulle_abondance ~ "Nulle",
      TRUE ~ NA_character_
    )) |>
    dplyr::filter(!is.na(class_abond)) |>
    dplyr::mutate(class_abond = factor(class_abond, levels = c("Faible","Moyen","Fort","Nulle")))
  if (!show_nulle_abondance) {
    abond_df <- dplyr::filter(abond_df, class_abond != "Nulle")
  }

  hydro_vars <- c("libelle_conditions_hydrologiques","libelle_turbidite","libelle_tendance_debit")
  hydro_df <- tidy_df |>
    dplyr::filter(variable %in% hydro_vars) |>
    dplyr::mutate(v = tolower(stringr::str_replace_all(stringr::str_trim(valeur), "[éèê]", "e"))) |>
    dplyr::mutate(class_hydro = dplyr::case_when(
      variable == "libelle_turbidite" & stringr::str_detect(v, "nul|faibl") ~ "Bas/Faible",
      variable == "libelle_turbidite" & stringr::str_detect(v, "moyen|modere") ~ "Moyen/Stable",
      variable == "libelle_turbidite" & stringr::str_detect(v, "fort|eleve|import") ~ "Haut/Fort",
      variable == "libelle_conditions_hydrologiques" & stringr::str_detect(v, "basse") ~ "Bas/Faible",
      variable == "libelle_conditions_hydrologiques" & stringr::str_detect(v, "haute|crue") ~ "Haut/Fort",
      variable == "libelle_conditions_hydrologiques" & stringr::str_detect(v, "moyen|norm") ~ "Moyen/Stable",
      variable == "libelle_tendance_debit" & stringr::str_detect(v, "baisse|decroi") ~ "Bas/Faible",
      variable == "libelle_tendance_debit" & stringr::str_detect(v, "stable") ~ "Moyen/Stable",
      variable == "libelle_tendance_debit" & stringr::str_detect(v, "hausse|croiss") ~ "Haut/Fort",
      TRUE ~ NA_character_
    )) |>
    dplyr::filter(!is.na(class_hydro)) |>
    dplyr::mutate(class_hydro = factor(class_hydro, levels = c("Bas/Faible","Moyen/Stable","Haut/Fort")))

  p <- ggplot2::ggplot()

  if (nrow(presence_df) > 0) {
    p <- p +
      ggplot2::geom_point(
        data = presence_df,
        ggplot2::aes(x = date_factor, y = forcats::fct_rev(variable), fill = val_presence),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke, na.rm = TRUE
      ) +
      ggplot2::scale_fill_manual(name = "Présence", values = c("Oui" = "#CC3399", "Non" = "grey90"), drop = FALSE) +
      ggnewscale::new_scale_fill()
  }
  if (nrow(abond_df) > 0) {
    p <- p +
      ggplot2::geom_point(
        data = abond_df,
        ggplot2::aes(x = date_factor, y = forcats::fct_rev(variable), fill = class_abond),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke, na.rm = TRUE
      ) +
      ggplot2::scale_fill_manual(name = "Abondance", values = abond_colors,
                                 breaks = c("Faible","Moyen","Fort"), drop = TRUE) +
      ggnewscale::new_scale_fill()
  }
  if (nrow(hydro_df) > 0) {
    p <- p +
      ggplot2::geom_point(
        data = hydro_df,
        ggplot2::aes(x = date_factor, y = forcats::fct_rev(variable), fill = class_hydro),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke, na.rm = TRUE
      ) +
      ggplot2::scale_fill_manual(name = "Hydrologie", values = hydro_colors,
                                 breaks = c("Bas/Faible","Moyen/Stable","Haut/Fort"), drop = FALSE)
  }

  p +
    ggplot2::scale_x_discrete(drop = FALSE) +
    ggplot2::theme_minimal(base_size = 13) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5),
                   axis.title.x = ggplot2::element_blank(),
                   axis.title.y = ggplot2::element_blank(),
                   legend.position = "right",
                   panel.grid = ggplot2::element_line(color = "grey95")) +
    ggplot2::labs(
      title = paste("Conditions / habitats —", if(!is.null(code_station)) code_station else code_point_prelevement_aspe),
      subtitle = paste0(annee_debut, "–", annee_fin)
    )
}

