# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme IPR par date d'opération
#'
#' @param yaml_config Chemin du YAML de connexion Postgres
#' @param station Code Sandre de la station (ex. "04199200")
#' @param annee_debut Année de début
#' @param annee_fin Année de fin (défaut = année courante)
#' @param schema Schéma SQL (défaut "qe")
#' @param title Titre du graphique (défaut "Notes IPR")
#' @param bar_width Largeur relative des barres (0–1, défaut 0.9)
#' @param n_last Nombre maximum de campagnes à afficher (limite aux N dernières dates distinctes)
#'
#' @return Un objet `ggplot2`
#'
#' @examples
#' \dontrun{
#' plot_ipr_histogram("C:/workspace/gwilenalim/yaml/config.yml", "04199200", 2000, n_last = 12)
#' }
#' @export
#' @noRd  
plot_ipr_histogram <- function(
  yaml_config,
  station,
  annee_debut,
  annee_fin  = as.numeric(format(Sys.Date(), "%Y")),
  schema    = "qe",
  title     = "Notes IPR",
  bar_width = 0.9,
  n_last    = 12
){
  con <- connect_pg(yaml_config)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ipr <- sprintf('"%s".aspe_ipr', schema_safe)
  tbl_ops <- sprintf('"%s".aspe_operations', schema_safe)

  sql <- paste0("
    WITH ipr_explicit AS (
      SELECT
        ipr.code_operation,
        ipr.code_station,
        ipr.resultat::double precision AS ipr
      FROM ", tbl_ipr, " ipr
      WHERE ipr.code_station = $1
        AND (ipr.lib_par ~* '(note|score)\\s*ipr' OR ipr.lib_par ~* '^ipr$')
    )
    SELECT
      (op.date_operation::timestamptz)::date AS date_op,
      e.ipr AS ipr,
      CASE
        WHEN e.ipr >= 0 AND e.ipr <= 5  THEN 'Très bon'
        WHEN e.ipr >  5 AND e.ipr <= 16 THEN 'Bon'
        WHEN e.ipr > 16 AND e.ipr <= 25 THEN 'Moyen'
        WHEN e.ipr > 25 AND e.ipr <= 36 THEN 'Médiocre'
        WHEN e.ipr > 36                  THEN 'Mauvais'
        ELSE 'Valeur manquante'
      END AS classe
    FROM ipr_explicit e
    JOIN ", tbl_ops, " op ON op.code_operation = e.code_operation
    WHERE EXTRACT(YEAR FROM (op.date_operation::timestamptz)) BETWEEN $2 AND $3
    ORDER BY date_op;
  ")

  df <- DBI::dbGetQuery(con, sql, params = list(station, as.integer(annee_debut), as.integer(annee_fin)))
  if (!nrow(df)) return(invisible(NULL))

  df$date_op    <- as.Date(df$date_op)
  df$label_date <- format(df$date_op, "%d/%m/%y")

  if (!is.null(n_last) && is.finite(n_last) && n_last > 0) {
    last_dates <- unique(df$date_op[order(df$date_op, decreasing = TRUE)])[1:n_last]
    df <- df[df$date_op %in% last_dates, , drop = FALSE]
  }

  levels_x <- unique(df$label_date[order(df$date_op)])
  df$label_date <- factor(df$label_date, levels = levels_x, ordered = TRUE)

  levels_classes <- c("Très bon","Bon","Moyen","Médiocre","Mauvais","Valeur manquante")
  df$classe <- factor(df$classe, levels = levels_classes, ordered = TRUE)
  palette <- c("Très bon"="blue","Bon"="green","Moyen"="yellow","Médiocre"="orange","Mauvais"="red","Valeur manquante"="grey70")

  ggplot2::ggplot(df, ggplot2::aes(x = label_date, y = ipr, fill = classe)) +
    ggplot2::geom_col(width = bar_width, color = "black", linewidth = 0.4) +
    ggplot2::scale_fill_manual(values = palette, limits = levels_classes, breaks = levels_classes, drop = FALSE, name = "Classe de\nqualité") +
    ggplot2::geom_hline(yintercept = c(5,16,25,36), linetype = "dashed", color = "grey40", linewidth = 0.3) +
    ggplot2::labs(title = title, x = NULL, y = NULL, fill = "Classe IPR") +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(panel.grid.minor = ggplot2::element_blank(),
                   ggplot2::element_text(angle = 90, hjust = 1))
}
