# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des longueurs pêchées de pêche ASPE pour une station
#'
#' Cette fonction interroge la base ASPE via un fichier YAML de connexion et
#' extrait les longueurs pêchées (`longueur`) issues de la table
#' `qe.aspe_operations` pour une station donnée (via `code_station`) ou pour un
#' point ASPE (`code_point_prelevement_aspe`).  
#' 
#' Si les deux identifiants sont fournis, `code_station` est prioritaire et un
#' warning est renvoyé.  
#'
#' Les données sont filtrées entre `annee_debut` et `annee_fin`, puis seules les
#' `n_last` dernières dates d’opération distinctes sont conservées.  
#'
#' La fonction produit un graphique ggplot2 de type histogramme (barres verticales)
#' où la hauteur des barres représente la profondeur (en mètres).  
#' Les dates sont affichées au format \%d/\%m/\%y, ordonnées chronologiquement,
#' et pivoteées de 90° pour faciliter la lecture.
#'
#' @param yaml_config Chemin vers le fichier YAML contenant les informations de
#'   connexion PostgreSQL.
#' @param code_station \[`character(1)`\]\  
#'   Code Sandre de la station. Si renseigné conjointement avec
#'   `code_point_prelevement_aspe`, il est prioritaire (avec warning).
#' @param code_point_prelevement_aspe \[`character(1)`\]\  
#'   Code du point de prélèvement ASPE utilisé si `code_station` n'est pas fourni.
#' @param annee_debut \[`numeric(1)`\]\  
#'   Année minimale des opérations à prendre en compte (défaut : 1950).
#' @param annee_fin \[`numeric(1)`\]\  
#'   Année maximale (défaut : année courante).
#' @param n_last \[`integer(1)`\]\  
#'   Nombre de dernières dates d’opérations (distinctes) à représenter.
#' @param titre \[`character(1)`\]\  
#'   Titre du graphique (défaut : `"Prof. moy. station (m)"`).
#'
#' @return Un objet ggplot2 représentant un histogramme des profondeurs
#'   de prélèvement. Retourne `NULL` si aucune donnée n’est disponible.
#'
#' @details
#' La table interrogée est : `qe.aspe_operations`, champ `profondeur`.  
#'
#' Les dates d’opération (`date_operation`) sont converties en classe `Date`,
#' puis ordonnées avant d’être transformées en facteur pour un affichage
#' strictement chronologique dans le graphique.  
#'
#' @examples
#' \dontrun{
#'plot_longueur_pechee_histogram(
#'  yaml_config = "C:/workspace/gwilenalim/yaml/config.yml",
#'  code_station = "04216050",
#'  annee_debut  = 2000,
#'  annee_fin    = 2025
#' )
#' }
#'
#' @export
plot_longueur_pechee_histogram <- function(
    yaml_config,
    code_station = NULL,
    code_point_prelevement_aspe = NULL,
    annee_debut = 1950,
    annee_fin = as.integer(format(Sys.Date(), "%Y")),
    n_last = 10,
    titre = "Longueur station (m)"
){
    library(DBI)
    library(dplyr)
    library(ggplot2)
    library(lubridate)

    # ----------------------------------------------------------------------
    # Gestion des paramètres code_station / code_point_prelevement_aspe
    # ----------------------------------------------------------------------

    if (!is.null(code_station) & !is.null(code_point_prelevement_aspe)) {
        warning("Les deux paramètres code_station et code_point_prelevement_aspe sont fournis. 
                Le code_station sera utilisé en priorité.")
    }

    # Choix du filtre
    use_station <- !is.null(code_station)

    # ----------------------------------------------------------------------
    # Connexion PG depuis YAML
    # ----------------------------------------------------------------------
     con <- connect_pg(yaml_config)
    on.exit(DBI::dbDisconnect(con))

    # ----------------------------------------------------------------------
    # Construction de la requête SQL
    # ----------------------------------------------------------------------

if (use_station) {
    # → On filtre via aspe_stations puis on rejoint les opérations
    sql <- glue::glue("
        SELECT
            s.code_station,
            o.date_operation::date AS date_op,
            o.longueur::float AS longueur
        FROM qe.aspe_operations o
        LEFT JOIN qe.aspe_stations s
            ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe
        WHERE s.code_station = '{code_station}'
          AND EXTRACT(YEAR FROM o.date_operation::date) BETWEEN {annee_debut} AND {annee_fin}
          AND o.longueur IS NOT NULL
        ORDER BY date_op DESC
    ")

} else {
    # → Recherche directe sur le point ASPE
    sql <- glue::glue("
        SELECT
            s.code_station,
            o.date_operation::date AS date_op,
            o.longueur::float AS longueur
        FROM qe.aspe_operations o
        LEFT JOIN qe.aspe_stations s
            ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe
        WHERE o.code_point_prelevement_aspe = '{code_point_prelevement_aspe}'
          AND EXTRACT(YEAR FROM o.date_operation) BETWEEN {annee_debut} AND {annee_fin}
          AND o.longueur IS NOT NULL
        ORDER BY date_op DESC
    ")
}

    df <- DBI::dbGetQuery(con, sql)

    if (nrow(df) == 0) {
        message("Aucune profondeur disponible pour les critères fournis.")
        return(NULL)
    }

    # ----------------------------------------------------------------------
    # Sélection des n dernières opérations à date unique
    # ----------------------------------------------------------------------
    df <- df %>%
        distinct(date_op, .keep_all = TRUE) %>%
        arrange(desc(date_op)) %>%
        slice(1:n_last) %>%
        arrange(date_op)

    # Facteur date formatée
    df$date_label <- format(df$date_op, "%d/%m/%y")
    df$date_label <- factor(df$date_label, levels = df$date_label)

    # ----------------------------------------------------------------------
    # Graphique
    # ----------------------------------------------------------------------
    p <- ggplot(df, aes(x = date_label, y = longueur)) +
        geom_col(fill = "grey30") +
        labs(title = titre,
             x = "",
             y = "") +
        theme_minimal(base_size = 12) +
        theme(
            axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
            plot.title = element_text(face = "bold")
        )

    return(p)
}
