# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Heatmap des conditions / habitats (présences, abondances, hydrologie)
#'
#' Produit une heatmap synthétique des habitats à partir des données
#' d'opérations ASPE, avec filtrage des typologies d'opération
#' (`libelle_qualification_operation`) via `exclure_typologies`.
#'
#' La fonction gère automatiquement :
#' - le mode station (code Sandre) ou CPP (code ASPE),
#' - les métadonnées pour construire le titre et le sous‑titre,
#' - la sélection des n dernières dates (distinctes),
#' - la catégorisation des valeurs : présence, abondance, hydrologie.
#'
#' @param yaml_path Chemin vers le fichier YAML de connexion PostgreSQL.
#' @param code_station Code Sandre de la station (ou `NULL` si CPP).
#' @param code_point_prelevement_aspe Code du point de prélèvement ASPE (ou `NULL` si station).
#' @param titre Titre personnalisé ; si `NULL`, il est construit automatiquement.
#' @param sous_titre Sous‑titre ; si `NULL`, il est généré automatiquement.
#' @param annee_debut Année de début (défaut 1950).
#' @param annee_fin Année de fin (défaut = année courante).
#' @param n_last Nombre de dates (opérations) à conserver (défaut: 12).
#' @param dot_size Taille des points.
#' @param dot_stroke Épaisseur du trait des points.
#' @param abond_colors Palette des classes d'abondance.
#' @param hydro_colors Palette des classes hydrologiques.
#' @param schema Schéma SQL (défaut `"qe"`).
#' @param exclure_typologies Vecteur des typologies d'opération à exclure
#'   (défaut = `"Incorrecte"`).
#'
#' @return Un objet ggplot2 représentant la heatmap (ou `NULL` si aucune donnée).
#' @export
plot_habitat_heatmap <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  titre = NULL,
  sous_titre = NULL,
  annee_debut = 1950,
  annee_fin   = lubridate::year(Sys.Date()),
  n_last = 12,
  dot_size = 6,
  dot_stroke = 0.6,
  abond_colors = c(Nulle = "white", Faible = "#CCFF99", Moyen = "#31a354", Fort = "#003300"),
  hydro_colors = c("Bas/Faible" = "#99FFFF", "Moyen/Stable" = "#0066CC", "Haut/Fort" = "#084594"),
  schema = "qe",
  exclure_typologies = c("Incorrecte")   # <-- [NOUVEAU]
){
  require(DBI); require(glue); require(dplyr); require(tidyr)
  require(lubridate); require(stringr); require(ggplot2); require(forcats)


  # Connexion

  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations',  schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',    schema_safe)


  # Choix mode STATION / CPP

  if (!is.null(code_station)) {
    mode      <- "station"
    filtre_sql <- "s.code_station = $1"
    join_sql   <- glue("JOIN {tbl_sta} s ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe")
    param1     <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    mode      <- "cpp"
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    join_sql   <- ""  # CPP orphelin
    param1     <- code_point_prelevement_aspe
  } else {
    stop("Fournir code_station OU code_point_prelevement_aspe.")
  }


  # Métadonnées → titre & sous‑titre auto

  if (is.null(titre) || is.null(sous_titre)) {

    if (mode == "station") {
      meta_sql <- glue("
        SELECT code_station, libelle_station,
               code_point_prelevement_wama, libelle_point_prelevement_wama
        FROM {tbl_sta} s WHERE s.code_station = $1 LIMIT 1
      ")
    } else {
      meta_sql <- glue("
        SELECT code_station, libelle_station,
               code_point_prelevement_wama, libelle_point_prelevement_wama
        FROM {tbl_sta} s WHERE s.code_point_prelevement_aspe = $1 LIMIT 1
      ")
    }

    meta <- DBI::dbGetQuery(con, meta_sql, params = list(param1))

    if (nrow(meta) == 1 && !is.na(meta$code_station) && nzchar(meta$code_station)) {
      titre_auto <- paste0(meta$code_station, " — ", meta$libelle_station)
    } else if (nrow(meta) == 1) {
      titre_auto <- paste0(meta$code_point_prelevement_wama, " — ", meta$libelle_point_prelevement_wama)
    } else {
      titre_auto <- param1
    }

    if (is.null(titre))      titre      <- paste("Conditions / habitats —", titre_auto)
    if (is.null(sous_titre)) sous_titre <- paste0(annee_debut, "–", annee_fin)
  }


  # Requête SQL + EXCLUSION TYPOLOGIES

  vars_habitats <- c(
    "abondance_abri_vegetal_aquatique","abondance_abris_rocheux","abondance_embacles_souches",
    "abondance_sous_berges","abondance_trous_fosses","abondance_vegetation_aquatique",
    "abondance_vegetation_bordure","facies_libelle_granulo_dominante","facies_libelle_granulo_accessoire",
    "facies_vegetation_dominante","libelle_conditions_hydrologiques","libelle_granulo_donnees_env_dominante",
    "libelle_granulo_donnees_env_accessoire","libelle_intensite_ombrage","libelle_tendance_debit","libelle_turbidite",
    "presence_curage","presence_deboisement","presence_diversite_ecoulement","presence_extraction_granulats",
    "presence_faucardage","presence_modification_morphologique","presence_repeuplement","presence_ripisylve_equilibree",
    "presence_secteur_canalise","presence_secteur_debit_reserve","presence_secteur_eclusee","presence_secteur_navigue",
    "presence_secteur_soutien_etiage","presence_sports_nautiques"
  )

  cols <- c("date_operation", vars_habitats)

  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT {paste(sprintf('o.%s', cols), collapse=', ')}
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND o.date_operation IS NOT NULL
      AND date_part('year', o.date_operation::timestamp) BETWEEN $2 AND $3
    ORDER BY o.date_operation::timestamp;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin)  
  )

  if (!nrow(df)) return(NULL)


  # Préparation des dates

  df <- df %>%
    mutate(date = as.Date(lubridate::as_datetime(date_operation, tz="UTC"))) %>%
    filter(!is.na(date)) %>%
    arrange(date)

if (!is.null(n_last) && n_last > 0) {
  last_dates <- df %>% distinct(date) %>% arrange(desc(date)) %>% slice(1:n_last) %>% pull(date)
  df <- df %>% filter(date %in% last_dates)
}

  if (!nrow(df)) return(NULL)

df <- df %>%
  arrange(date) %>%                          # <-- tri croissant explicite après filtre
  mutate(
    date_label  = format(date, "%d/%m/%y"),
    date_factor = factor(date_label, levels = unique(date_label))  # niveaux = ordre chrono
  )


  # Extraction / pivot / catégorisation

  vars_presentes <- vars_habitats[vars_habitats %in% names(df)]
  is_non_empty <- function(x) any(!is.na(x) & stringr::str_trim(as.character(x)) != "")

  vars_non_vides <- vars_presentes[vapply(df[vars_presentes], is_non_empty, logical(1))]
  if (!length(vars_non_vides)) return(NULL)

  tidy_df <- df %>%
    select(date, date_factor, all_of(vars_non_vides)) %>%
    pivot_longer(
      cols = all_of(vars_non_vides),
      names_to = "variable",
      values_to = "valeur"
    ) %>%
    mutate(valeur = na_if(trimws(as.character(valeur)), ""))


  # Présence

  presence_df <- tidy_df %>%
    filter(str_starts(variable, "presence_")) %>%
    mutate(v = tolower(valeur)) %>%
    mutate(val_presence = case_when(
      v %in% c("oui","true","vrai","yes") ~ "Oui",
      v %in% c("non","false","faux","no") ~ "Non",
      TRUE ~ NA_character_
    )) %>%
    filter(!is.na(val_presence)) %>%
    mutate(val_presence = factor(val_presence, levels=c("Non","Oui")))


  # Abondance

  abond_df <- tidy_df %>%
    filter(str_starts(variable, "abondance_")) %>%
    mutate(v = tolower(stringr::str_replace_all(valeur, "[éèê]", "e"))) %>%
    mutate(class_abond = case_when(
      str_detect(v, "faibl") ~ "Faible",
      str_detect(v, "moyen|modere") ~ "Moyen",
      str_detect(v, "fort|eleve|import") ~ "Fort",
      str_detect(v, "nul") ~ "Nulle"
    )) %>%
    filter(!is.na(class_abond)) %>%
    mutate(class_abond = factor(class_abond, levels=c("Faible","Moyen","Fort","Nulle")))


  # Hydrologie

  hydro_vars <- c("libelle_conditions_hydrologiques","libelle_turbidite","libelle_tendance_debit")

  hydro_df <- tidy_df %>%
    filter(variable %in% hydro_vars) %>%
    mutate(v = tolower(stringr::str_replace_all(valeur, "[éèê]", "e"))) %>%
    mutate(class_hydro = case_when(
      # turbidité
      variable == "libelle_turbidite"              & str_detect(v,"nul|faibl")    ~ "Bas/Faible",
      variable == "libelle_turbidite"              & str_detect(v,"moyen")        ~ "Moyen/Stable",
      variable == "libelle_turbidite"              & str_detect(v,"fort|eleve")   ~ "Haut/Fort",

      # conditions hydrologiques
      variable == "libelle_conditions_hydrologiques" & str_detect(v,"basse")      ~ "Bas/Faible",
      variable == "libelle_conditions_hydrologiques" & str_detect(v,"haute|crue") ~ "Haut/Fort",
      variable == "libelle_conditions_hydrologiques" & str_detect(v,"moyen|norm") ~ "Moyen/Stable",

      # tendance débit
      variable == "libelle_tendance_debit"        & str_detect(v,"baisse")        ~ "Bas/Faible",
      variable == "libelle_tendance_debit"        & str_detect(v,"stable")        ~ "Moyen/Stable",
      variable == "libelle_tendance_debit"        & str_detect(v,"hausse")        ~ "Haut/Fort"
    )) %>%
    filter(!is.na(class_hydro)) %>%
    mutate(class_hydro = factor(class_hydro, levels=c("Bas/Faible","Moyen/Stable","Haut/Fort")))


  # Construction du graphique final

  p <- ggplot()

  if (nrow(presence_df) > 0)
    p <- p +
      geom_point(
        data = presence_df,
        aes(x = date_factor, y = fct_rev(variable), fill = val_presence),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke
      ) +
      scale_fill_manual(values = c("Oui"="#CC3399", "Non"="grey90"), name="Présence") +
      ggnewscale::new_scale_fill()

  if (nrow(abond_df) > 0)
    p <- p +
      geom_point(
        data = abond_df,
        aes(x = date_factor, y = fct_rev(variable), fill = class_abond),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke
      ) +
      scale_fill_manual(values = abond_colors, name="Abondance") +
      ggnewscale::new_scale_fill()

  if (nrow(hydro_df) > 0)
    p <- p +
      geom_point(
        data = hydro_df,
        aes(x = date_factor, y = fct_rev(variable), fill = class_hydro),
        shape = 21, color = "black", size = dot_size, stroke = dot_stroke
      ) +
      scale_fill_manual(values = hydro_colors, name="Hydrologie")

  p +
    scale_x_discrete(drop = FALSE) +
    labs(title = titre, subtitle = sous_titre) +
    theme_bw(base_size = 13) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      axis.title  = element_blank(),
      panel.grid  = element_line(color = "grey95"),
      plot.title    = element_text(size = 11, face = "bold"),
      plot.subtitle = element_text(size = 10)
    )
}


