# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des métriques IPR (Observé vs Modélisé)
#'
#' @param yaml_config Chemin du YAML de connexion
#' @param station Code Sandre de la station
#' @param indicateurs Vecteur parmi `c("DII","DIO","DIT","DTI","NEL","NER","NTE")`
#' @param annee_debut Année de début (défaut 1970)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param schema Schéma SQL (défaut "qe")
#' @param table Nom de la table IPR (défaut "aspe_ipr")
#' @param n_lignes_facets Nb de lignes pour `facet_wrap()` (défaut 2)
#' @param show_labels Afficher des étiquettes numériques sur les barres
#' @param label_digits Précision des labels (1 par défaut)
#' @param label_big_mark Séparateur de milliers (" ")
#' @param label_decimal_mark Séparateur décimal (",")
#' @param label_size Taille de police des labels (3.2)
#' @param label_fontface Graisse ("plain")
#' @param n_last Nombre de dernières dates (opérations) à afficher (12)
#' @param return_data Si TRUE, renvoie `list(plot=..., data=...)`; sinon le `ggplot`
#'
#' @return ggplot2::ggplot (ou `list`)
#'
#' @examples
#' \dontrun{
#' plot_ipr_metrics(".../config.yml", "04199200", c("NER","NEL","DTI"), 2000, 2025, n_last = 12)
#' }
#' @export
#' @noRd  
plot_ipr_metrics <- function(
  yaml_config,
  station,
  indicateurs = c("DII","DIO","DIT","DTI","NEL","NER","NTE"),
  annee_debut   = 1970,
  annee_fin     = as.numeric(format(Sys.Date(), "%Y")),
  schema       = "qe",
  table        = "aspe_ipr",
  n_lignes_facets = 2,
  show_labels  = FALSE,
  label_digits = 1,
  label_big_mark = " ",
  label_decimal_mark = ",",
  label_size   = 3.2,
  label_fontface = "plain",
  n_last       = 12,
  return_data  = FALSE
){
  autorises <- c("DII","DIO","DIT","DTI","NEL","NER","NTE")
  indicateurs <- toupper(indicateurs)
  if (any(!indicateurs %in% autorises)) {
    stop(glue::glue(
      "Indicateur(s) invalide(s): {paste(setdiff(indicateurs, autorises), collapse=', ')}. ",
      "Choix possibles: {paste(autorises, collapse=', ')}."
    ), call. = FALSE)
  }

  con <- connect_pg(yaml_config)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  schema_q <- DBI::dbQuoteIdentifier(con, schema_safe)
  table_q  <- DBI::dbQuoteIdentifier(con, table)

  libpars_cibles <- sort(unique(c(indicateurs, paste0(indicateurs, "_obs"))))
  lib_in <- paste(DBI::dbQuoteString(con, libpars_cibles), collapse = ", ")

  sql <- glue::glue("
    SELECT date, lib_par, resultat
    FROM {schema_q}.{table_q}
    WHERE code_station = $1
      AND EXTRACT(YEAR FROM date) BETWEEN $2 AND $3
      AND lib_par IN ({lib_in})
    ORDER BY date ASC;
  ")

  df <- DBI::dbGetQuery(con, sql, params = list(station, as.integer(annee_debut), as.integer(annee_fin)))
  if (!nrow(df)) return(NULL)

  df_plot <- df |>
    dplyr::mutate(
      type     = dplyr::if_else(stringr::str_detect(lib_par, "_obs$"), "Observé", "Modélisé"),
      metrique = stringr::str_replace(lib_par, "_obs$", ""),
      date     = as.Date(date),
      date_lab = format(date, "%d/%m/%y")
    ) |>
    dplyr::arrange(date) |>
    dplyr::group_by(date, date_lab, metrique, type) |>
    dplyr::summarise(valeur = dplyr::first(resultat), .groups = "drop") |>
    dplyr::filter(metrique %in% indicateurs)

  if (!is.null(n_last) && is.finite(n_last) && n_last > 0) {
    last_dates <- df_plot |>
      dplyr::distinct(date) |>
      dplyr::arrange(dplyr::desc(date)) |>
      dplyr::slice(1:n_last) |>
      dplyr::pull(date)
    df_plot <- df_plot |>
      dplyr::filter(date %in% last_dates) |>
      dplyr::arrange(date)
    lvl_x <- df_plot |>
      dplyr::distinct(date, date_lab) |>
      dplyr::arrange(date) |>
      dplyr::pull(date_lab)
    df_plot <- df_plot |>
      dplyr::mutate(date_lab = factor(date_lab, levels = unique(lvl_x)))
  } else {
    lvl_x <- df_plot |>
      dplyr::distinct(date, date_lab) |>
      dplyr::arrange(date) |>
      dplyr::pull(date_lab)
    df_plot <- df_plot |>
      dplyr::mutate(date_lab = factor(date_lab, levels = unique(lvl_x)))
  }

  df_plot <- df_plot |>
    dplyr::mutate(metrique = factor(metrique, levels = indicateurs))

  labels_metriques <- c(
    "NER" = "nb d'esp. rhéophiles",
    "NEL" = "nb d'esp. lithophiles",
    "NTE" = "nb total d'espèces",
    "DIT" = "densité ind. tolérants",
    "DIO" = "densité ind. invertivores",
    "DII" = "densité ind. omnivores",
    "DTI" = "densité totale d'ind."
  )

  p <- ggplot2::ggplot(df_plot, ggplot2::aes(x = date_lab, y = valeur, fill = type)) +
    ggplot2::geom_col(position = ggplot2::position_dodge(width = 0.8), colour = "black", width = 0.75) +
    ggplot2::scale_fill_manual(name = NULL, values = c("Observé" = "grey60", "Modélisé" = "white"), drop = FALSE) +
    ggplot2::facet_wrap(~ metrique, nrow = n_lignes_facets, scales = "free_y",
                        labeller = ggplot2::labeller(metrique = labels_metriques)) +
    ggplot2::labs(title = "Métriques IPR", x = "", y = "") +
    ggplot2::theme_bw(base_size = 12) +
    ggplot2::theme(legend.position = "bottom",
                   axis.text.x = ggplot2::element_text(angle = 90, hjust = 1),
                   panel.grid.minor = ggplot2::element_blank(),
                   strip.background = ggplot2::element_rect(fill = "grey95", colour = "grey70")) +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0.02, 0.15)))

  if (isTRUE(show_labels)) {
    fmt_fun <- scales::number_format(
      accuracy = if (label_digits > 0) 10^-label_digits else 1,
      big.mark = label_big_mark,
      decimal.mark = label_decimal_mark,
      trim = TRUE
    )
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = fmt_fun(valeur)),
      position = ggplot2::position_dodge(width = 0.8),
      vjust = -0.4, size = label_size, fontface = label_fontface
    )
  }
  if (isTRUE(return_data)) list(plot = p, data = df_plot) else p
}

