# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme IPR par date d'opération (sécurisé)
#'
#' @param yaml_path Chemin du YAML de connexion Postgres
#' @param station Code Sandre de la station
#' @param annee_debut Année de début
#' @param annee_fin Année de fin
#' @param schema Schéma SQL
#' @param title Titre du graphique
#' @param bar_width Largeur des barres
#' @param n_last Nombre max de campagnes
#' @param exclure_typologies Vecteur des typologies d'opérations à exclure
#'        (défaut = "Incorrecte", les autres typologies sont "Incertaine",
#'        "Non qualifié" et "Correcte")
#'
#' @export
plot_ipr_histogram <- function(
  yaml_path,
  station,
  annee_debut,
  annee_fin  = as.numeric(format(Sys.Date(), "%Y")),
  schema     = "qe",
  title      = "Notes IPR",
  bar_width  = 0.9,
  n_last     = 12,
  exclure_typologies = c("Incorrecte")
){
  require(DBI); require(glue); require(dplyr); require(ggplot2)


  # 1) Connexion

  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ipr  <- sprintf('"%s".aspe_ippr',        schema_safe)
  tbl_ops  <- sprintf('"%s".aspe_operations', schema_safe)


  # 2) Requête SQL avec exclusion typologies

  placeholders <- paste(rep("?", length(exclure_typologies)), collapse = ",")
  
  sql <- glue::glue("
    WITH ipr_explicit AS (
      SELECT
        ipr.code_operation,
        ipr.code_station,
        ipr.resultat::double precision AS ipr
      FROM {tbl_ipr} ipr
      WHERE ipr.code_station = $1
        AND (
          ipr.lib_par ~* '(note|score)\\s*ipr'
          OR ipr.lib_par ~* '^ipr$'
        )
    )
    SELECT
      (op.date_operation::timestamptz)::date AS date_op,
      e.ipr AS ipr,
      CASE
        WHEN e.ipr >= 0 AND e.ipr <= 5  THEN 'Très bon'
        WHEN e.ipr >  5 AND e.ipr <= 16 THEN 'Bon'
        WHEN e.ipr > 16 AND e.ipr <= 25 THEN 'Moyen'
        WHEN e.ipr > 25 AND e.ipr <= 36 THEN 'Médiocre'
        WHEN e.ipr > 36                  THEN 'Mauvais'
        ELSE 'Valeur manquante'
      END AS classe
    FROM ipr_explicit e
    JOIN {tbl_ops} op
      ON op.code_operation = e.code_operation
    WHERE EXTRACT(YEAR FROM op.date_operation::timestamptz)
          BETWEEN $2 AND $3
      AND op.libelle_qualification_operation NOT IN ({placeholders})
    ORDER BY date_op;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = c(list(station, 
                    annee_debut, 
                    annee_fin), 
               as.list(exclure_typologies))
  )

  if (!nrow(df)) return(invisible(NULL))


  # 3) Préparation & graphique (inchangé)

  df$date_op    <- as.Date(df$date_op)
  df$label_date <- format(df$date_op, "%d/%m/%y")

  if (!is.null(n_last) && is.finite(n_last) && n_last > 0) {
    last_dates <- unique(df$date_op[order(df$date_op, decreasing = TRUE)])[1:n_last]
    df <- df[df$date_op %in% last_dates, , drop = FALSE]
  }

  levels_x <- unique(df$label_date[order(df$date_op)])
  df$label_date <- factor(df$label_date, levels = levels_x, ordered = TRUE)

  levels_classes <- c("Très bon","Bon","Moyen","Médiocre","Mauvais","Valeur manquante")
  df$classe <- factor(df$classe, levels = levels_classes, ordered = TRUE)

  palette <- c(
    "Très bon" = "blue",
    "Bon"      = "green",
    "Moyen"    = "yellow",
    "Médiocre" = "orange",
    "Mauvais"  = "red",
    "Valeur manquante" = "grey70"
  )

  ggplot(df, aes(x = label_date, y = ipr, fill = classe)) +
    geom_col(width = bar_width, color = "black", linewidth = 0.4) +
    scale_fill_manual(values = palette, limits = levels_classes, drop = FALSE) +
    geom_hline(yintercept = c(5,16,25,36), linetype = "dashed", color = "grey40") +
    labs(title = title, x = NULL, y = NULL) +
    theme_bw(base_size = 12) +
    theme(
      panel.grid.minor = element_blank(),
      axis.text.x      = element_text(angle = 90, hjust = 1)
    )
}

