# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Heatmap faunistique (ASPE) – Abondances par date et taxon regroupé
#'
#' @param yaml_path Chemin du fichier YAML contenant la connexion PostgreSQL
#' @param code_station Code Sandre de la station (optionnel)
#' @param code_point_prelevement_aspe Code ASPE du point de prélèvement (optionnel)
#' @param annee_debut Année minimale (défaut = 1950)
#' @param annee_fin Année maximale (défaut = année courante)
#' @param n_last Nombre de dernières opérations (dates distinctes) à conserver.
#'              NULL = toutes (défaut).
#' @param fill_colors Vecteur de couleurs pour le dégradé. Défaut = séquentiel bleu.
#' @param titre Titre du graphique. Par défaut "Effectif — <code>" (station ou point ASPE).
#' @param sous_titre Sous-titre du graphique (optionnel)
#' @param file_out Chemin de sauvegarde (PNG) si non NULL
#' @param width Largeur (pouces), défaut A4 paysage
#' @param height Hauteur (pouces), défaut A4 paysage
#' @param dpi DPI pour l'export
#'
#' @return Un objet ggplot2 représentant la heatmap
#' @export
plot_faune_heatmap <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin = lubridate::year(Sys.Date()),
  n_last = NULL,
  fill_colors = c("#f7fbff","#c6dbef","#6baed6","#2171b1","#08519c"),
  titre = NULL,
  sous_titre = NULL,
  file_out   = NULL,
  width      = 29.7 / 2.54,
  height     = 21 / 2.54,
  dpi        = 300

){

  # ---- Connexion PG ----
  y <- yaml::read_yaml(yaml_path)
  y$port        <- y$port        %||% 5432
  y$sslmode     <- y$sslmode     %||% "prefer"
  y$search_path <- y$search_path %||% "qe,public"

  con <- DBI::dbConnect(
    RPostgres::Postgres(),
    dbname = y$dbname, host = y$host, port = y$port,
    user = y$user, password = y$password,
    sslmode = y$sslmode,
    options = sprintf("-c search_path=%s", y$search_path)
  )
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  # ---- Filtre station vs point ----
  if (!is.null(code_station)) {
    filtre_sql <- "s.code_station = $1"
    param1 <- code_station
    code_defaut <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"
    param1 <- code_point_prelevement_aspe
    code_defaut <- code_point_prelevement_aspe
  } else {
    stop("Fournir code_station OU code_point_prelevement_aspe.")
  }

  # Titre par défaut si non fourni

info_titres <- .aspe_fetch_meta_and_titles(
    con = con,
    schema = schema,
    station = code_station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    default_title_suffix = " — Effectifs capturés par opération",
    default_subtitle_prefix = "Synthèse réalisée le "
  )

  if (is.null(titre)) {
    titre <- info_titres$titre_auto
  }
  if (is.null(sous_titre)) {
    sous_titre <- info_titres$sous_titre_auto
  }


  # ---- Requête SQL ----
  sql <- sprintf("
    SELECT 
      o.date_operation,
      lt.nom_commun_taxon,
      lt.code_alternatif_taxon,
      lt.code_lot,
      lt.effectif_lot::integer
    FROM qe.aspe_liste_taxons lt
    JOIN qe.aspe_operations o 
         ON lt.code_operation = o.code_operation
    JOIN qe.aspe_stations s
         ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe
    WHERE %s
      AND o.date_operation IS NOT NULL
      AND date_part('year', CAST(o.date_operation AS timestamp)) BETWEEN $2 AND $3
    ORDER BY CAST(o.date_operation AS timestamp)
  ", filtre_sql)

  df <- DBI::dbGetQuery(con, sql, params = list(param1, annee_debut, annee_fin))
  if (!nrow(df)) return(NULL)

  # ---- Nettoyage dates ----
  df <- df %>%
    dplyr::mutate(date = as.Date(lubridate::as_datetime(date_operation, tz = "UTC"))) %>%
    dplyr::filter(!is.na(date))

  # ---- Règles de regroupements taxonomiques ----
  rules <- list(
    BRB = "BRE",
    CAS = "CAX", CAG = "CAX", CAD = "CAX", CAA = "CAX",
    CCU = "CCO", CMI = "CCO",
    CHP = "CHA",
    GOL = "GOX", GOO = "GOX", GOU = "GOX",
    TRL = "TRF", TRM = "TRF",
    VAI = "PHX", VAC = "PHX", VAB = "PHX",
    VAR = "VAN"
  )

  df$taxon_group <- dplyr::recode(df$code_alternatif_taxon, !!!rules, .default = df$code_alternatif_taxon)

  # ---- Agrégation correcte (dédoublonnage de lots) ----
  agg <- df %>%
    dplyr::distinct(date, taxon_group, code_lot, effectif_lot, nom_commun_taxon, .keep_all = TRUE) %>%
    dplyr::group_by(date, taxon_group, code_lot) %>%
    dplyr::summarise(effectif_lot = sum(effectif_lot, na.rm = TRUE), .groups = "drop") %>%
    dplyr::group_by(date, taxon_group) %>%
    dplyr::summarise(
      effectif_total = sum(effectif_lot, na.rm = TRUE),
      code_lots = paste(sort(unique(code_lot)), collapse = ", "),
      .groups = "drop"
    )

  # ---- Étiquette "nom commun" par groupe (nom le plus fréquent) ----
  name_map <- df %>%
    dplyr::group_by(taxon_group, nom_commun_taxon) %>%
    dplyr::summarise(n = dplyr::n(), .groups = "drop_last") %>%
    dplyr::arrange(taxon_group, dplyr::desc(n)) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup() %>%
    dplyr::transmute(taxon_group, label_taxon = nom_commun_taxon)

  agg <- agg %>%
    dplyr::left_join(name_map, by = "taxon_group") %>%
    dplyr::mutate(label_taxon = dplyr::coalesce(label_taxon, taxon_group))

  # ---- Filtrage des n dernières opérations ----
  if (!is.null(n_last) && is.numeric(n_last) && n_last > 0) {
    last_dates <- agg %>%
      dplyr::distinct(date) %>%
      dplyr::arrange(dplyr::desc(date)) %>%
      dplyr::slice(1:n_last) %>%
      dplyr::pull(date)

    agg <- agg %>% dplyr::filter(date %in% last_dates)
  }

  # ---- Formatage des dates & gestion des zéros pour l'échelle log ----
  agg <- agg %>%
    dplyr::mutate(
      date_label  = format(date, "%d/%m/%y"),
      date_factor = factor(date_label, levels = unique(date_label), ordered = TRUE),
      fill_value  = ifelse(effectif_total <= 0, NA_real_, effectif_total) # log10 ne gère pas 0
    )

  # ---- Heatmap ----
  p <- ggplot2::ggplot(agg, ggplot2::aes(
    x = date_factor,
    y = forcats::fct_rev(label_taxon),
    fill = fill_value
  )) +
    ggplot2::geom_tile(color = "grey70") +

    # Valeur numérique centrée (en blanc)
    ggplot2::geom_text(ggplot2::aes(label = effectif_total), color = "black", size = 3.2) +

    # Dégradé personnalisable + échelle log10 + couleur des NA (zéros)
    ggplot2::scale_fill_gradientn(
      colours = fill_colors,
      trans   = "log10",
      name    = "Effectif (log10)",
      na.value = "grey90"
    ) +
    ggplot2::theme_bw(base_size = 13) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5),
      axis.title.x = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      panel.grid = ggplot2::element_blank(),
      legend.position = "none"
    ) +
    ggplot2::labs(
      title = titre,
      subtitle = sous_titre
    )

      if (!is.null(file_out)) {
    ggsave(filename = file_out, 
           plot = p, 
           width = width, 
           height = height, 
           dpi = dpi, 
           bg = "white")
  }
  
  return(p)
}


