# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des conductivités ASPE pour une station ou un CPP
#'
#' Extrait les conductivités instantanées (`conductivite`) depuis la table
#' `aspe_operations`, filtrées selon :
#' - une station (`code_station`) **ou** un point ASPE (`code_point_prelevement_aspe`) ;
#' - un intervalle d'années (`annee_debut` – `annee_fin`) ;
#' - un filtre d'exclusion de typologies via le champ
#'   `libelle_qualification_operation` (`exclure_typologies`) ;
#' - les `n_last` dernières dates distinctes.
#'
#' Produit un histogramme ggplot2 où chaque barre représente la conductivité
#' (µS/cm), avec dates ordonnées chronologiquement et pivotées à 90°.
#'
#' @param yaml_path Chemin vers le fichier YAML de connexion PostgreSQL.
#' @param code_station Code Sandre (prioritaire si fourni).
#' @param code_point_prelevement_aspe Code du point ASPE (si `code_station` est NULL).
#' @param annee_debut Année minimale (défaut = 1950).
#' @param annee_fin Année maximale (défaut = année courante).
#' @param n_last Nombre de dernières dates distinctes à afficher (défaut = 10).
#' @param titre Titre du graphique (défaut `"Conductivité (µS/cm)"`).
#' @param schema Schéma SQL (défaut `"qe"`).
#' @param exclure_typologies Vecteur des typologies d’opérations à exclure
#'   (défaut `"Incorrecte"`).
#'
#' @return Un ggplot2 ou `NULL` si aucune donnée.
#' @export
plot_conductivite_pechee_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Conductivité (µS/cm)",
  schema      = "qe",
  exclure_typologies = c("Incorrecte")   # <-- [NOUVEAU PARAMÈTRE]
){
  library(DBI); library(dplyr); library(ggplot2)
  library(lubridate); library(glue)

  
  # 1) Validation des paramètres
  
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("Les deux identifiants sont fournis : priorité au code_station.")
  }
  use_station <- !is.null(code_station)

  
  # 2) Connexion PG
  
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations',  schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',    schema_safe)

  
  # 3) Logique station / CPP (CPP = PAS DE JOIN !)
  
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s 
                        ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else {
    join_sql   <- ""  # CPP orphelin → aucun JOIN
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  
  # 4) SQL sécurisé + filtre typologique
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.conductivite::float  AS conductivite
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
      AND NOT (o.libelle_qualification_operation = ANY($4))   -- <-- [NOUVEAU]
      AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN $2 AND $3
      AND o.conductivite IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin, exclure_typologies)  # <-- [NOUVEAU]
  )

  if (nrow(df) == 0) {
    message("Aucune conductivité disponible pour les critères fournis.")
    return(NULL)
  }

  
  # 5) n dernières dates distinctes
  
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(
    format(df$date_op, "%d/%m/%y"),
    levels = format(df$date_op, "%d/%m/%y")
  )

  
  # 6) Graphique
  
  ggplot(df, aes(x = date_label, y = conductivite)) +
    geom_col(fill = "grey30") +
    labs(title = titre, x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}
