# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des faciès (Courant / Plat / Profond)
#'
#' @param yaml_path Chemin YAML
#' @param code_station Code Sandre de la station (ou NULL si `code_point_prelevement_aspe` fourni)
#' @param code_point_prelevement_aspe Code du point ASPE (ou NULL si `code_station` fourni)
#' @param annee_debut Année de début (défaut 1900)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param n_last Nombre d'opérations (dates distinctes) à afficher
#'
#' @return Un `ggplot2` (ou `NULL` si aucune donnée)
#'
#' @examples
#' \dontrun{
#' plot_facies_importance(".../config.yml", code_station = "04207400", annee_debut = 1950, n_last = 12)
#' }
#' @export
plot_facies_importance <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = NULL,
  annee_fin   = lubridate::year(Sys.Date()),
  n_last = 12
){
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  if (!is.null(code_station)) {
    filtre_sql <- "s.code_station = $1"; param1 <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"; param1 <- code_point_prelevement_aspe
  } else stop("Veuillez fournir code_station OU code_point_prelevement_aspe.", call. = FALSE)

  if (is.null(annee_debut)) annee_debut <- 1900

  sql <- sprintf("
    SELECT 
      o.date_operation, 
      o.facies_importance_relative, 
      o.facies_libelle_type
    FROM qe.aspe_operations o
    JOIN qe.aspe_stations s 
      ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe
    WHERE %s
      AND o.date_operation IS NOT NULL
      AND date_part('year', CAST(o.date_operation AS timestamp)) BETWEEN $2 AND $3
    ORDER BY CAST(o.date_operation AS timestamp);
  ", filtre_sql)

  df_all <- DBI::dbGetQuery(con, sql, params = list(param1, annee_debut, annee_fin))
  if (!nrow(df_all)) return(NULL)

  df_all <- df_all |>
    dplyr::mutate(
      date = as.Date(lubridate::as_datetime(date_operation)),
      date_label = format(date, "%d/%m/%y")
    ) |>
    dplyr::arrange(date)

  last_dates <- df_all |> dplyr::distinct(date) |> dplyr::arrange(dplyr::desc(date)) |> dplyr::slice(1:n_last) |> dplyr::pull(date)
  df <- df_all |> dplyr::filter(date %in% last_dates) |> dplyr::arrange(date)
  if (!nrow(df)) return(NULL)

  dates_ref <- df |> dplyr::distinct(date, date_label)

  decode_relative <- function(x){
    if (is.null(x) || length(x) == 0 || is.na(x) || trimws(x) == "") return(NULL)
    x_raw <- x
    x <- gsub("^\\\\x", "", x)
    x <- gsub("[^0-9 ]", "", x)
    x_trim <- trimws(x)
    if (grepl("^\\\\x\\s", x_raw)) {
      x_trim <- paste0("0", gsub(" ", "", x_trim))
    } else {
      x_trim <- gsub(" ", "", x_trim)
    }
    if (nchar(x_trim) == 0 || nchar(x_trim) %% 2 != 0) return(NULL)
    vals <- stringr::str_extract_all(x_trim, "..")[[1]]
    vals <- as.numeric(vals)
    if (any(is.na(vals))) return(NULL)
    if (abs(sum(vals) - 100) > 1e-6) return(NULL)
    vals
  }

  decode_modalites <- function(x){
    if (is.null(x) || is.na(x) || trimws(x) == "") return(NULL)
    x <- gsub("^\\\\x", "", x)
    x <- stringr::str_squish(x)
    parts <- unlist(stringr::str_split(x, "\\s+"))
    parts <- stringr::str_trim(parts)
    parts[parts == "Profonds"] <- "Profond"
    parts
  }

  tidy <- df |>
    dplyr::rowwise() |>
    dplyr::mutate(
      valeurs   = list(decode_relative(facies_importance_relative)),
      modalites = list(decode_modalites(facies_libelle_type)),
      ok        = !is.null(valeurs) && !is.null(modalites) && length(valeurs) == length(modalites)
    ) |>
    dplyr::ungroup()

  long_valid <- tidy |>
    dplyr::filter(ok) |>
    tidyr::unnest(cols = c(valeurs, modalites)) |>
    dplyr::filter(modalites %in% c("Courant","Plat","Profond"))

  all_facies <- c("Courant","Plat","Profond")
  grid <- tidyr::crossing(dates_ref, modalites = all_facies)

  long <- grid |>
    dplyr::left_join(long_valid, by = c("date","date_label","modalites")) |>
    dplyr::mutate(valeurs = dplyr::coalesce(valeurs, 0)) |>
    dplyr::mutate(date_label = factor(date_label, levels = dates_ref$date_label))

  facies_colors <- c("Courant"="#6D76F8","Plat"="#7FDD4C","Profond"="#C72C48")

  ggplot2::ggplot(long, ggplot2::aes(x = date_label, y = valeurs, fill = modalites)) +
    ggplot2::geom_col(color = "black") +
    ggplot2::scale_fill_manual(values = facies_colors, name = "Faciès", drop = FALSE, na.translate = FALSE) +
    ggplot2::labs(title = "Importance relative des faciès", x = NULL, y = "Pourcentage") +
    ggplot2::theme_bw(base_size = 13) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1),
                   panel.grid.minor = ggplot2::element_blank())
}


