# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des profondeurs de prélèvement ASPE pour une station
#'
#' Cette fonction interroge la base ASPE via un fichier YAML de connexion et
#' extrait les profondeurs de prélèvement (`profondeur`) issues de la table
#' `qe.aspe_operations` pour une station donnée (via `code_station`) ou pour un
#' point ASPE (`code_point_prelevement_aspe`).  
#' 
#' Si les deux identifiants sont fournis, `code_station` est prioritaire et un
#' warning est renvoyé.  
#'
#' Les données sont filtrées entre `annee_debut` et `annee_fin`, puis seules les
#' `n_last` dernières dates d’opération distinctes sont conservées.  
#'
#' La fonction produit un graphique ggplot2 de type histogramme (barres verticales)
#' où la hauteur des barres représente la profondeur (en mètres).  
#' Les dates sont affichées au format \%d/\%m/\%y, ordonnées chronologiquement,
#' et pivoteées de 90° pour faciliter la lecture.
#'
#' @param yaml_path Chemin vers le fichier YAML contenant les informations de
#'   connexion PostgreSQL.
#' @param code_station \[`character(1)`\]\  
#'   Code Sandre de la station. Si renseigné conjointement avec
#'   `code_point_prelevement_aspe`, il est prioritaire (avec warning).
#' @param code_point_prelevement_aspe \[`character(1)`\]\  
#'   Code du point de prélèvement ASPE utilisé si `code_station` n'est pas fourni.
#' @param annee_debut \[`numeric(1)`\]\  
#'   Année minimale des opérations à prendre en compte (défaut : 1950).
#' @param annee_fin \[`numeric(1)`\]\  
#'   Année maximale (défaut : année courante).
#' @param n_last \[`integer(1)`\]\  
#'   Nombre de dernières dates d’opérations (distinctes) à représenter.
#' @param titre \[`character(1)`\]\  
#'   Titre du graphique (défaut : `"Prof. moy. station (m)"`).
#'
#' @return Un objet ggplot2 représentant un histogramme des profondeurs
#'   de prélèvement. Retourne `NULL` si aucune donnée n’est disponible.
#'
#' @details
#' La table interrogée est : `qe.aspe_operations`, champ `profondeur`.  
#'
#' Les dates d’opération (`date_operation`) sont converties en classe `Date`,
#' puis ordonnées avant d’être transformées en facteur pour un affichage
#' strictement chronologique dans le graphique.  
#'
#' @examples
#' \dontrun{
#' plot_profondeur_histogram(
#'   yaml_path = "config/connexion.yml",
#'   code_station = "04216000",
#'   annee_debut = 2000,
#'   n_last = 12
#' )
#' }
#'
#' @export
plot_profondeur_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Prof. moy. station (m)",
  schema      = "qe"
){
  library(DBI)
  library(dplyr)
  library(ggplot2)
  library(lubridate)
  library(glue)

  # --------------------------------------------------------------------
  # 1) Validation des paramètres
  # --------------------------------------------------------------------
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("Les deux paramètres sont fournis : priorité au code_station.")
  }

  use_station <- !is.null(code_station)

  # --------------------------------------------------------------------
  # 2) Connexion et sécurisation
  # --------------------------------------------------------------------
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations', schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations', schema_safe)

  # --------------------------------------------------------------------
  # 3) Logique station / CPP — CPP = PAS DE JOIN !
  # --------------------------------------------------------------------
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else {
    join_sql   <- ""   # CPP orphelin → surtout AUCUN JOIN
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  # --------------------------------------------------------------------
  # 4) Requête SQL sécurisée CPP‑proof
  # --------------------------------------------------------------------
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.profondeur::float    AS profondeur
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
      AND EXTRACT(YEAR FROM o.date_operation::date) BETWEEN $2 AND $3
      AND o.profondeur IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(con, sql, params = list(param1, annee_debut, annee_fin))

  if (nrow(df) == 0) {
    message("Aucune profondeur disponible pour les critères fournis.")
    return(NULL)
  }

  # --------------------------------------------------------------------
  # 5) n dernières dates uniques
  # --------------------------------------------------------------------
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(format(df$date_op, "%d/%m/%y"),
                          levels = format(df$date_op, "%d/%m/%y"))

  # --------------------------------------------------------------------
  # 6) Graphique
  # --------------------------------------------------------------------
  ggplot(df, aes(x = date_label, y = profondeur)) +
    geom_col(fill = "grey30") +
    labs(title = titre, x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}
