# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des profondeurs par faciès (ASPE)
#'
#' Cette fonction extrait les profondeurs moyennes de faciès
#' (`facies_profondeur_moyenne`) et les types de faciès (`facies_libelle_type`)
#' depuis `aspe_operations`, pour une station ou un point ASPE.
#'
#' Elle nettoie les chaînes (retrait du préfixe "\\x", découpages, normalisation
#' des noms de faciès) puis met en correspondance profondeurs et faciès.
#'
#' Le filtrage tient compte :
#' - du code station ou CPP,
#' - d’un intervalle d’années,
#' - des `n_last` dernières opérations distinctes,
#' - des typologies d’opérations à exclure (`libelle_qualification_operation`).
#'
#' Le résultat est un histogramme où chaque date affiche une ou plusieurs barres
#' (position dodge), avec une couleur par type de faciès.
#'
#' @param yaml_path Chemin YAML de connexion PG
#' @param code_station Code Sandre (prioritaire si fourni)
#' @param code_point_prelevement_aspe Code ASPE si pas de station
#' @param annee_debut Année minimale (défaut 1950)
#' @param annee_fin Année maximale (défaut = année courante)
#' @param n_last Nombre de dernières dates distinctes (défaut 10)
#' @param titre Titre du graphique
#' @param schema Schéma SQL (défaut "qe")
#' @param exclure_typologies Vecteur des typologies d’opérations à exclure
#'
#' @return Un ggplot2 ou NULL
#' @export
plot_facies_profondeur_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin = as.integer(format(Sys.Date(), "%Y")),
  n_last = 10,
  titre = "Profondeurs par faciès",
  schema = "qe",
  exclure_typologies = c("Incorrecte")
){
  library(DBI); library(dplyr); library(ggplot2)
  library(stringr); library(tidyr); library(glue)

  # Helpers compatibles fusen
  clean_depths <- function(x) {
    x2 <- str_remove(x, "^\\\\x")
    x2 <- str_squish(x2)
    vals <- str_split(x2, "\\s+")[[1]]
    suppressWarnings(as.numeric(vals))
  }

  clean_facies <- function(x) {
    x2 <- str_remove(x, "^\\\\x")
    x2 <- str_squish(x2)
    x2 <- str_replace_all(x2, " ", "")
    fac <- str_split(x2, "(?=[A-Z])")[[1]]
    fac <- fac[fac != "" & !is.na(fac)]
    ifelse(grepl("^Profond", fac, ignore.case = TRUE), "Profond", fac)
  }

  expand_match <- function(date_op, date_label, depths, facies){
    nd <- length(depths); nf <- length(facies)
    if (nd == nf) {
      tibble(date_op=date_op, date_label=date_label, profondeur=depths, facies=facies)
    } else if (nd > nf) {
      tibble(date_op=date_op, date_label=date_label,
             profondeur=depths,
             facies=rep(facies, length.out=nd))
    } else {
      tibble(date_op=date_op, date_label=date_label,
             profondeur=rep(depths, length.out=nf),
             facies=facies)
    }
  }

  # Connexion PG
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations',  schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',    schema_safe)

  if (!is.null(code_station)) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    join_sql   <- ""
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  } else {
    stop("Veuillez fournir code_station OU code_point_prelevement_aspe.")
  }

  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.facies_profondeur_moyenne,
      o.facies_libelle_type
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND EXTRACT(YEAR FROM o.date_operation::date)
            BETWEEN $2 AND $3
      AND o.facies_profondeur_moyenne IS NOT NULL
      AND o.facies_libelle_type IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con, sql,
    params=list(param1, annee_debut, annee_fin)
  )
  if (nrow(df) == 0) return(NULL)

  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- format(df$date_op, "%d/%m/%y")

  df$depths_list  <- lapply(df$facies_profondeur_moyenne, clean_depths)
  df$facies_list  <- lapply(df$facies_libelle_type,       clean_facies)

  # Expansion SANS pipe et SANS mutate(list(...))
  long_df <- bind_rows(
    lapply(seq_len(nrow(df)), function(i){
      expand_match(
        df$date_op[i],
        df$date_label[i],
        df$depths_list[[i]],
        df$facies_list[[i]]
      )
    })
  )

  facies_colors <- c(
    "Courant" = "#6D76F8",
    "Plat"    = "#7FDD4C",
    "Profond" = "#C72C48"
  )

  ggplot(long_df, aes(x = factor(date_label), y = profondeur, fill = facies)) +
    geom_col(position = position_dodge(width = 0.8)) +
    scale_fill_manual(values = facies_colors, drop = FALSE) +
    labs(
      title = titre,
      x = "",
      y = "Profondeur (m)",
      fill = "Faciès"
    ) +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}


#' Histogramme des faciès (Courant / Plat / Profond)
#'
#' @param yaml_path Chemin YAML
#' @param code_station Code Sandre de la station (ou NULL si `code_point_prelevement_aspe` fourni)
#' @param code_point_prelevement_aspe Code du point ASPE (ou NULL si `code_station` fourni)
#' @param annee_debut Année de début (défaut 1900)
#' @param annee_fin Année de fin (défaut = année courante)
#' @param n_last Nombre d'opérations (dates distinctes) à afficher
#' @param exclure_typologies Vecteur des typologies d’opérations à exclure
#'   (défaut `"Incorrecte"`).
#'
#' @return Un `ggplot2` (ou `NULL` si aucune donnée)
#'
#' @examples
#' \dontrun{
#' plot_facies_importance(".../config.yml", code_station = "04207400", annee_debut = 1950, n_last = 12)#' plot_facies_importance(".../config.yml", code_station = "04207400", annee_debut = 1950, n_last = 12)
#' }
#' @export
plot_facies_importance <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = NULL,
  annee_fin   = lubridate::year(Sys.Date()),
  n_last = 12,
  exclure_typologies= c("Incorrecte") 
){
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  if (!is.null(code_station)) {
    filtre_sql <- "s.code_station = $1"; param1 <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql <- "s.code_point_prelevement_aspe = $1"; param1 <- code_point_prelevement_aspe
  } else stop("Veuillez fournir code_station OU code_point_prelevement_aspe.", call. = FALSE)

  if (is.null(annee_debut)) annee_debut <- 1900

  
  excl_clause <- if (length(exclure_typologies) > 0) {
    quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
    glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
  } else ""

  sql <- glue::glue("
    SELECT
      o.date_operation,
      o.facies_importance_relative,
      o.facies_libelle_type
    FROM {tbl_ops} o
    JOIN {tbl_sta} s
      ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe
    WHERE {filtre_sql}
      AND o.date_operation IS NOT NULL
      AND date_part('year', CAST(o.date_operation AS timestamp)) BETWEEN $2 AND $3
    {excl_clause}
    ORDER BY CAST(o.date_operation AS timestamp);
  ")

  df_all <- DBI::dbGetQuery(con, sql, params = list(param1, annee_debut, annee_fin))
  if (!nrow(df_all)) return(NULL)


  df_all <- df_all |>
    dplyr::mutate(
      date = as.Date(lubridate::as_datetime(date_operation)),
      date_label = format(date, "%d/%m/%y")
    ) |>
    dplyr::arrange(date)

  last_dates <- df_all |> dplyr::distinct(date) |> dplyr::arrange(dplyr::desc(date)) |> dplyr::slice(1:n_last) |> dplyr::pull(date)
  df <- df_all |> dplyr::filter(date %in% last_dates) |> dplyr::arrange(date)
  if (!nrow(df)) return(NULL)

  dates_ref <- df |> dplyr::distinct(date, date_label)

  decode_relative <- function(x){
    if (is.null(x) || length(x) == 0 || is.na(x) || trimws(x) == "") return(NULL)
    x_raw <- x
    x <- gsub("^\\\\x", "", x)
    x <- gsub("[^0-9 ]", "", x)
    x_trim <- trimws(x)
    if (grepl("^\\\\x\\s", x_raw)) {
      x_trim <- paste0("0", gsub(" ", "", x_trim))
    } else {
      x_trim <- gsub(" ", "", x_trim)
    }
    if (nchar(x_trim) == 0 || nchar(x_trim) %% 2 != 0) return(NULL)
    vals <- stringr::str_extract_all(x_trim, "..")[[1]]
    vals <- as.numeric(vals)
    if (any(is.na(vals))) return(NULL)
    if (abs(sum(vals) - 100) > 1e-6) return(NULL)
    vals
  }

  decode_modalites <- function(x){
    if (is.null(x) || is.na(x) || trimws(x) == "") return(NULL)
    x <- gsub("^\\\\x", "", x)
    x <- stringr::str_squish(x)
    parts <- unlist(stringr::str_split(x, "\\s+"))
    parts <- stringr::str_trim(parts)
    parts[parts == "Profonds"] <- "Profond"
    parts
  }

  tidy <- df |>
    dplyr::rowwise() |>
    dplyr::mutate(
      valeurs   = list(decode_relative(facies_importance_relative)),
      modalites = list(decode_modalites(facies_libelle_type)),
      ok        = !is.null(valeurs) && !is.null(modalites) && length(valeurs) == length(modalites)
    ) |>
    dplyr::ungroup()

  long_valid <- tidy |>
    dplyr::filter(ok) |>
    tidyr::unnest(cols = c(valeurs, modalites)) |>
    dplyr::filter(modalites %in% c("Courant","Plat","Profond"))

  all_facies <- c("Courant","Plat","Profond")
  grid <- tidyr::crossing(dates_ref, modalites = all_facies)

  long <- grid |>
    dplyr::left_join(long_valid, by = c("date","date_label","modalites")) |>
    dplyr::mutate(valeurs = dplyr::coalesce(valeurs, 0)) |>
    dplyr::mutate(date_label = factor(date_label, levels = dates_ref$date_label))

  facies_colors <- c("Courant"="#6D76F8","Plat"="#7FDD4C","Profond"="#C72C48")

  ggplot2::ggplot(long, ggplot2::aes(x = date_label, y = valeurs, fill = modalites)) +
    ggplot2::geom_col(color = "black") +
    ggplot2::scale_fill_manual(values = facies_colors, name = "Faciès", drop = FALSE, na.translate = FALSE) +
    ggplot2::labs(title = "Importance relative des faciès", x = NULL, y = "Pourcentage") +
    ggplot2::theme_bw(base_size = 13) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1),
                   panel.grid.minor = ggplot2::element_blank())
}
