# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Histogramme des surfaces de pêche ASPE pour une station ou un CPP
#'
#' Extrait les surfaces pêchées (`surface_calculee`) depuis la table
#' `aspe_operations` après filtrage :
#' - par station (`code_station`) OU par point ASPE (`code_point_prelevement_aspe`) ;
#' - par période (`annee_debut` – `annee_fin`) ;
#' - par exclusion des typologies d’opération (`libelle_qualification_operation`)
#'   via l’argument `exclure_typologies` ;
#' - par les `n_last` dernières dates distinctes.
#'
#' Retourne un histogramme ggplot2 où chaque barre représente la surface de pêche
#' (en m²), avec des dates chronologiques pivotées à 90° pour améliorer la lisibilité.
#'
#' @param yaml_path Chemin YAML (connexion PostgreSQL).
#' @param code_station Code Sandre de la station (prioritaire si fourni).
#' @param code_point_prelevement_aspe Code du point ASPE (utilisé si `code_station` est NULL).
#' @param annee_debut Année minimale (défaut 1950).
#' @param annee_fin Année maximale (défaut = année courante).
#' @param n_last Nombre de dernières dates à afficher (défaut 10).
#' @param titre Titre du graphique (défaut `"Surface pêchée en m²"`).
#' @param schema Schéma SQL contenant `aspe_operations` (défaut `"qe"`).
#' @param exclure_typologies Vecteur de typologies d’opération à **exclure**
#'   (défaut `"Incorrecte"`).
#'
#' @return Un objet ggplot2 ou `NULL` si aucune donnée.
#' @export
plot_surface_pechee_histogram <- function(
  yaml_path,
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin   = as.integer(format(Sys.Date(), "%Y")),
  n_last      = 10,
  titre       = "Surface pêchée en m²",
  schema      = "qe",
  exclure_typologies = c("Incorrecte")    # <-- [NOUVEAU]
){
  library(DBI); library(dplyr); library(ggplot2)
  library(lubridate); library(glue)

  
  # 1) Validation
  
  if (!is.null(code_station) && !is.null(code_point_prelevement_aspe)) {
    warning("code_station et code_point_prelevement_aspe fournis : priorité à code_station.")
  }

  use_station <- !is.null(code_station)

  
  # 2) Connexion
  
  con <- connect_pg(yaml_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  tbl_ops <- sprintf('"%s".aspe_operations', schema_safe)
  tbl_sta <- sprintf('"%s".aspe_stations',   schema_safe)

  
  # 3) Mode station / CPP
  
  if (use_station) {
    join_sql   <- glue("LEFT JOIN {tbl_sta} s ON s.code_point_prelevement_aspe = o.code_point_prelevement_aspe")
    filtre_sql <- "s.code_station = $1"
    param1     <- code_station
  } else {
    join_sql   <- ""  # CPP orphelin → aucun JOIN
    filtre_sql <- "o.code_point_prelevement_aspe = $1"
    param1     <- code_point_prelevement_aspe
  }

  
  # 4) SQL sécurisé + EXCLUSION TYPOLOGIES
  
  excl_clause <- if (length(exclure_typologies) > 0) {
  quoted <- paste(DBI::dbQuoteString(con, exclure_typologies), collapse = ", ")
  glue::glue("AND NOT (o.libelle_qualification_operation IN ({quoted}))")
} else ""
  
  sql <- glue("
    SELECT
      o.date_operation::date AS date_op,
      o.surface_calculee::float AS surface_calculee
    FROM {tbl_ops} o
    {join_sql}
    WHERE {filtre_sql}
    {excl_clause}
      AND EXTRACT(YEAR FROM o.date_operation::date) BETWEEN $2 AND $3
      AND o.surface_calculee IS NOT NULL
    ORDER BY date_op DESC;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin) 
  )

  if (nrow(df) == 0) {
    message("Aucune surface disponible pour les critères fournis.")
    return(NULL)
  }

  
  # 5) Limiter aux n dernières dates distinctes
  
  df <- df %>%
    distinct(date_op, .keep_all = TRUE) %>%
    arrange(desc(date_op)) %>%
    slice(1:n_last) %>%
    arrange(date_op)

  df$date_label <- factor(
    format(df$date_op, "%d/%m/%y"),
    levels = format(df$date_op, "%d/%m/%y")
  )

  
  # 6) Plot
  
  ggplot(df, aes(x = date_label, y = surface_calculee)) +
    geom_col(fill = "grey30") +
    labs(title = titre, x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      plot.title  = element_text(face = "bold")
    )
}
