# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' @noRd
plot_ipr_metrics <- function(
  yaml_path,
  station,
  indicateurs = c("DII","DIO","DIT","DTI","NEL","NER","NTE"),
  annee_debut   = 1970,
  annee_fin     = as.numeric(format(Sys.Date(), "%Y")),
  schema        = "qe",
  table         = "aspe_ipr",
  n_lignes_facets = 2,
  show_labels   = FALSE,
  label_digits  = 1,
  label_big_mark     = " ",
  label_decimal_mark = ",",
  label_size    = 3.2,
  label_fontface = "plain",
  n_last        = 12,
  return_data   = FALSE,
  exclure_typologies = c("Incorrecte")   # <- [NOUVEAU PARAMÈTRE]
){
  require(DBI); require(glue); require(dplyr)
  require(ggplot2); require(stringr)


  # 1) Validation des indicateurs

  autorises <- c("DII","DIO","DIT","DTI","NEL","NER","NTE")
  indicateurs <- toupper(indicateurs)

  if (any(!indicateurs %in% autorises)) {
    stop(glue::glue(
      "Indicateur(s) invalide(s): {paste(setdiff(indicateurs, autorises), collapse=', ')}. ",
      "Choix possibles: {paste(autorises, collapse=', ')}."
    ), call. = FALSE)
  }


  # 2) Connexion & sécurisation schéma/table

  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)
  table_safe  <- sanitize_schema(table)

  tbl_full <- sprintf('"%s"."%s"', schema_safe, table_safe)
  tbl_ops  <- sprintf('"%s".aspe_operations', schema_safe)  # <- [NOUVEAU]


  # 3) Libellés cibles (modélisé & observé)

  libpars_cibles <- sort(unique(c(indicateurs, paste0(indicateurs, "_obs"))))
  lib_in <- paste(DBI::dbQuoteString(con, libpars_cibles), collapse = ", ")


  # 4) SQL : ajout JOIN opérations + filtre typologies

  sql <- glue::glue("
    SELECT 
      ipr.date,
      ipr.lib_par,
      ipr.resultat
    FROM {tbl_full} ipr
    JOIN {tbl_ops} op
      ON op.code_operation = ipr.code_operation             
    WHERE ipr.code_station = $1
      AND EXTRACT(YEAR FROM ipr.date) BETWEEN $2 AND $3
      AND ipr.lib_par IN ({lib_in})
      AND NOT (op.libelle_qualification_operation = ANY($4)) 
    ORDER BY ipr.date ASC;
  ")

  df <- DBI::dbGetQuery(
    con, sql,
    params = list(station, as.integer(annee_debut), as.integer(annee_fin), exclure_typologies)  
  )
  if (!nrow(df)) return(NULL)

  # 5) Préparation des données

  df_plot <- df %>%
    mutate(
      type     = if_else(str_detect(lib_par, "_obs$"), "Observé", "Modélisé"),
      metrique = str_replace(lib_par, "_obs$", ""),
      date     = as.Date(date),
      date_lab = format(date, "%d/%m/%y")
    ) %>%
    arrange(date) %>%
    group_by(date, date_lab, metrique, type) %>%
    summarise(valeur = first(resultat), .groups="drop") %>%
    filter(metrique %in% indicateurs)


  # 6) Limiter aux n dernières dates

  if (!is.null(n_last) && is.finite(n_last) && n_last > 0) {
    last_dates <- df_plot %>%
      distinct(date) %>%
      arrange(desc(date)) %>%
      slice(1:n_last) %>%
      pull(date)
    df_plot <- df_plot %>% filter(date %in% last_dates) %>% arrange(date)
  }

  # Ordres
  lvl_x <- df_plot %>%
    distinct(date, date_lab) %>%
    arrange(date) %>%
    pull(date_lab)

  df_plot <- df_plot %>%
    mutate(
      date_lab = factor(date_lab, levels = unique(lvl_x)),
      metrique = factor(metrique, levels = indicateurs)
    )


  # 7) Labels métiers

  labels_metriques <- c(
    "NER" = "nb d'esp. rhéophiles",
    "NEL" = "nb d'esp. lithophiles",
    "NTE" = "nb total d'espèces",
    "DIT" = "densité ind. tolérants",
    "DIO" = "densité ind. invertivores",
    "DII" = "densité ind. omnivores",
    "DTI" = "densité totale d'ind."
  )


  # 8) Graphique

  p <- ggplot2::ggplot(df_plot, aes(x = date_lab, y = valeur, fill = type)) +
    geom_col(
      position = position_dodge(width = 0.8),
      colour = "black", width = 0.75
    ) +
    scale_fill_manual(
      name = NULL,
      values = c("Observé" = "grey60", "Modélisé" = "white"),
      drop   = FALSE
    ) +
    facet_wrap(
      ~ metrique,
      nrow = n_lignes_facets,
      scales = "free_y",
      labeller = labeller(metrique = labels_metriques)
    ) +
    labs(title = "Métriques IPR", x = "", y = "") +
    theme_bw(base_size = 12) +
    theme(
      legend.position = "bottom",
      axis.text.x = element_text(angle = 90, hjust = 1),
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = "grey95", colour = "grey70")
    ) +
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.15)))


  # 9) Labels facultatifs

  if (isTRUE(show_labels)) {
    fmt_fun <- scales::number_format(
      accuracy     = if (label_digits > 0) 10^-label_digits else 1,
      big.mark     = label_big_mark,
      decimal.mark = label_decimal_mark,
      trim = TRUE
    )
    p <- p + geom_text(
      aes(label = fmt_fun(valeur)),
      position = position_dodge(width = 0.8),
      vjust = -0.4,
      size = label_size,
      fontface = label_fontface
    )
  }

  if (isTRUE(return_data))
    return(list(plot = p, data = df_plot))

  return(p)
}
