# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Heatmap faunistique (ASPE) – Abondances par date et taxon regroupé
#'
#' Produit une heatmap des effectifs de poissons capturés par opération,
#' regroupés par taxon et par date, avec :
#' - station OU CPP,
#' - n dernières dates,
#' - regroupements taxonomiques standardisés,
#' - affichage des valeurs (effectifs) + échelle log10,
#' - exclusion optionnelle de typologies d'opérations via
#'   `libelle_qualification_operation` (ex. "Incorrecte").
#'
#' @param yaml_path Chemin du YAML de connexion PostgreSQL
#' @param schema Schéma SQL (défaut "qe")
#' @param code_station Code Sandre (si fourni, prioritaire)
#' @param code_point_prelevement_aspe Code ASPE si `code_station` est NULL
#' @param annee_debut Année minimale (défaut 1950)
#' @param annee_fin Année maximale (défaut année courante)
#' @param n_last Nombre de dernières opérations distinctes (NULL = toutes)
#' @param fill_colors Palette du dégradé
#' @param titre Titre du graphique (défaut auto)
#' @param sous_titre Sous-titre (défaut auto)
#' @param file_out Export PNG (optionnel)
#' @param width Hauteur du PNG
#' @param height Largeur du PNG
#' @param dpi DPI
#' @param exclure_typologies Vecteur des typologies à exclure
#'
#' @return Un objet ggplot2 (heatmap)
#' @export
plot_faune_heatmap <- function(
  yaml_path,
  schema = "qe",
  code_station = NULL,
  code_point_prelevement_aspe = NULL,
  annee_debut = 1950,
  annee_fin = lubridate::year(Sys.Date()),
  n_last = NULL,
  fill_colors = c("#f7fbff","#c6dbef","#6baed6","#2171b1","#08519c"),
  titre = NULL,
  sous_titre = NULL,
  file_out   = NULL,
  width      = 29.7 / 2.54,
  height     = 21 / 2.54,
  dpi        = 300,
  exclure_typologies = c("Incorrecte")   # <-- [NOUVEAU]
){

  
  # Connexion
  
  con <- connect_pg(yaml_path)
  on.exit(try(DBI::dbDisconnect(con), silent = TRUE), add = TRUE)

  schema_safe <- sanitize_schema(schema)

  
  # Filtre station / CPP
  
  if (!is.null(code_station)) {
    filtre_sql  <- "s.code_station = $1"
    param1      <- code_station
    code_defaut <- code_station
  } else if (!is.null(code_point_prelevement_aspe)) {
    filtre_sql  <- "s.code_point_prelevement_aspe = $1"
    param1      <- code_point_prelevement_aspe
    code_defaut <- code_point_prelevement_aspe
  } else {
    stop("Fournir code_station OU code_point_prelevement_aspe.")
  }

  
  # Titres auto
  
  info_titres <- .aspe_fetch_meta_and_titles(
    con = con,
    schema = schema_safe,
    station = code_station,
    code_point_prelevement_aspe = code_point_prelevement_aspe,
    default_title_suffix = "\nEffectifs capturés par opération",
    default_subtitle_prefix = "Synthèse réalisée le "
  )

  if (is.null(titre))      titre      <- info_titres$titre_auto
  if (is.null(sous_titre)) sous_titre <- info_titres$sous_titre_auto

  
  # SQL + EXCLUSION TYPOLOGIES
  
  sql <- glue::glue("
    SELECT 
      o.date_operation,
      lt.nom_commun_taxon,
      lt.code_alternatif_taxon,
      lt.code_lot,
      lt.effectif_lot::integer
    FROM \"{schema_safe}\".aspe_liste_taxons lt
    JOIN \"{schema_safe}\".aspe_operations o 
         ON lt.code_operation = o.code_operation
    JOIN \"{schema_safe}\".aspe_stations s
         ON o.code_point_prelevement_aspe = s.code_point_prelevement_aspe
    WHERE {filtre_sql}
      AND NOT (o.libelle_qualification_operation = ANY($4))   -- <-- [NOUVEAU]
      AND o.date_operation IS NOT NULL
      AND date_part('year', o.date_operation::timestamp)
            BETWEEN $2 AND $3
    ORDER BY o.date_operation;
  ")

  df <- DBI::dbGetQuery(
    con,
    sql,
    params = list(param1, annee_debut, annee_fin, exclure_typologies)  # <-- [NOUVEAU]
  )
  if (!nrow(df)) return(NULL)

  
  # Traitements identiques à ta version
  
  df <- df %>%
    dplyr::mutate(date = as.Date(lubridate::as_datetime(date_operation)))

  # Règles de regroupement taxonomique
  rules <- list(
    BRB = "BRE",
    CAS = "CAX", CAG = "CAX", CAD = "CAX", CAA = "CAX",
    CCU = "CCO", CMI = "CCO",
    CHP = "CHA",
    GOL = "GOX", GOO = "GOX", GOU = "GOX",
    TRL = "TRF", TRM = "TRF",
    VAI = "PHX", VAC = "PHX", VAB = "PHX",
    VAR = "VAN"
  )
  df$taxon_group <- dplyr::recode(
    df$code_alternatif_taxon, !!!rules,
    .default = df$code_alternatif_taxon
  )

  # Agrégation (lots -> taxon_group)
  agg <- df %>%
    dplyr::distinct(date, taxon_group, code_lot, effectif_lot,
                    nom_commun_taxon, .keep_all = TRUE) %>%
    dplyr::group_by(date, taxon_group, code_lot) %>%
    dplyr::summarise(effectif_lot = sum(effectif_lot, na.rm = TRUE),
                     .groups = "drop") %>%
    dplyr::group_by(date, taxon_group) %>%
    dplyr::summarise(
      effectif_total = sum(effectif_lot, na.rm = TRUE),
      .groups = "drop"
    )

  # Nom commun dominant
  name_map <- df %>%
    dplyr::group_by(taxon_group, nom_commun_taxon) %>%
    dplyr::summarise(n = dplyr::n(), .groups = "drop_last") %>%
    dplyr::arrange(taxon_group, dplyr::desc(n)) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup() %>%
    dplyr::transmute(taxon_group, label_taxon = nom_commun_taxon)

  agg <- agg %>%
    dplyr::left_join(name_map, by = "taxon_group") %>%
    dplyr::mutate(label_taxon = dplyr::coalesce(label_taxon, taxon_group))

  # Limitation n_last
  if (!is.null(n_last) && n_last > 0) {
    last_dates <- agg %>%
      dplyr::distinct(date) %>%
      dplyr::arrange(dplyr::desc(date)) %>%
      dplyr::slice(1:n_last) %>%
      dplyr::pull(date)

    agg <- agg %>% dplyr::filter(date %in% last_dates)
  }

  # Formatage
  agg <- agg %>%
    dplyr::mutate(
      date_label  = format(date, "%d/%m/%y"),
      date_factor = factor(date_label, levels = unique(date_label)),
      fill_value  = ifelse(effectif_total <= 0, NA_real_, effectif_total)
    )

  
  # Heatmap ggplot2
  
  p <- ggplot2::ggplot(
    agg,
    ggplot2::aes(x = date_factor, y = forcats::fct_rev(label_taxon), fill = fill_value)
  ) +
    ggplot2::geom_tile(color = "grey70") +
    ggplot2::geom_text(aes(label = effectif_total), color = "black", size = 3.2) +
    ggplot2::scale_fill_gradientn(
      colours = fill_colors,
      trans   = "log10",
      name    = "Effectif (log10)",
      na.value = "grey90"
    ) +
    ggplot2::theme_bw(base_size = 13) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5),
      axis.title  = ggplot2::element_blank(),
      panel.grid  = ggplot2::element_blank(),
      legend.position = "none"
    ) +
    ggplot2::labs(title = titre, subtitle = sous_titre)

  if (!is.null(file_out)) {
    ggplot2::ggsave(file_out, p, width = width, height = height, dpi = dpi, bg = "white")
  }

  return(p)
}

