# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Regroupe les néotaxons selon les règles du script IPR 1.0.5
#'
#' Cette fonction applique les clés de correspondance définies dans le script
#' officiel de calcul de l’Indice Poissons Rivière (IPR) version 1.0.5 afin de
#' regrouper les taxons ASPE en néotaxons.  
#' 
#' Chaque taxon en entrée est recherché dans une table de conversion codée en dur
#' au sein de la fonction. Si une correspondance existe, le taxon est remplacé
#' par son code néotaxon regroupé. Si aucune correspondance n'est trouvée,
#' la fonction renvoie le taxon d'origine sans modification.  
#'
#' L'objectif est de garantir l’homogénéité des regroupements de taxons dans les
#' traitements IPR, conformément aux spécifications de la version 1.0.5, où
#' plusieurs taxons élémentaires (ex. *BRB*, *BRE*) sont associés à un même
#' néotaxon (ex. *BRX*).
#'
#' @param codes Un vecteur de caractères contenant des codes taxons ASPE (ex. : `"BRB"`, `"VAR"`, `"ANG"`).
#'
#' @return Un vecteur de même longueur que \code{codes}, dans lequel chaque taxon
#' est remplacé par son code néotaxon regroupé lorsqu'une correspondance existe,
#' ou laissé inchangé sinon.
#'
#' @details
#' La table interne de correspondance reproduit fidèlement les regroupements
#' utilisés dans l'IPR 1.0.5 pour les besoins du calcul des métriques.  
#' Elle inclut notamment :
#' \itemize{
#'   \item les regroupements des brèmes (\code{BRB}, \code{BRE} → \code{BRX}),
#'   \item les chabots et chevesnes (\code{CHA}, \code{CHF}, \code{CHP}, etc. → \code{CHX}),
#'   \item les vairons (\code{VAI}, \code{VAC}, \code{VAB}, etc. → \code{PHX}),
#'   \item les loches (\code{LOF}, \code{LOL}, \code{LOQ}, etc. → \code{LOX}),
#'   \item et tous les regroupements additionnels strictement définis dans la version 1.0.5.
#' }
#'
#' Aucune modification n’est apportée aux codes taxons absents de la table
#' de regroupement, conformément au comportement attendu du script IPR.
#'
#' @examples
#' regroupe_taxons_ipr(c("BRB", "CAA", "ANG", "VAR", "XXX"))
#' # Résultat :
#' # [1] "BRX" "CAX" "ANG" "VAX" "XXX"
#'
#' @export
regroupe_taxons_ipr <- function(codes) {
  
  # Table de regroupement codée en dur
  IPR_REGROUP_MAP <- c(
    BRB="BRX", BRE="BRX",
    BRO="ESX", BRA="ESX",
    CAS="CAX", CAG="CAX", CAD="CAX", CAA="CAX",
    CCU="CCO", CMI="CCO",
    CHA="CHX", CHF="CHX", CHP="CHX", CHB="CHX", CHH="CHX", CHD="CHX", CHR="CHX",
    CHE="SQX", CHC="SQX",
    GOL="GOX", GOO="GOX", GOU="GOX",
    LOF="LOX", LOL="LOX", LOQ="LOX", LOH="LOX",
    EPT="PUX", EPL="PUX",
    LPP="LPX", LPR="LPX", LPM="LPX",
    OBR="OBX", OBA="OBX",
    TRL="TRF", TRM="TRF",
    VAI="PHX", VAC="PHX", VAB="PHX", VAD="PHX", VAG="PHX", VAL="PHX",
    VAR="VAX", VAN="VAX", VAA="VAX"
  )
  
  # Application du mapping
  mapped <- IPR_REGROUP_MAP[codes]
  
  # Pour les codes sans correspondance : renvoyer le code d'entrée
  mapped[is.na(mapped)] <- codes[is.na(mapped)]
  
  return(mapped)
}
