# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Nettoyer un nom de schéma SQL (A–Z a–z 0–9 _)
#'
#' @param schema Chaîne de caractères
#' @return Chaîne nettoyée contenant uniquement `[A-Za-z0-9_]`
#' @keywords internal
#' @noRd
#' @export 
sanitize_schema <- function(schema) {
  gsub("[^A-Za-z0-9_]", "", schema)
}
